Repository serverless-stack/sst, pull requests merged in 2021-08, with the labels that each got.

#640 EventBus: add high level construct for AWS EventBridge
  README.md
  packages/cli/test/playground/lib/eventbus-stack.ts
  packages/cli/test/playground/lib/index.ts
  packages/resources/src/EventBus.ts
  packages/resources/src/index.ts
  packages/resources/src/util/permission.ts
  packages/resources/test/EventBus.test.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/EventBus.md
  www/docs/constructs/Function.md
  www/sidebars.js
Labels: enhancement

#636 Support copyFiles regardless of runtime
  packages/resources/src/Function.ts
  packages/resources/src/util/goBuilder.ts
  packages/resources/src/util/nodeBuilder.ts
  packages/resources/src/util/python/bundling.ts
  packages/resources/src/util/pythonBuilder.ts
  packages/resources/test/Function.test.ts
Labels: enhancement

#643 Bulk run prettier on codebase
  .git-blame-ignore-revs
  .github/workflows/ci.yml
  CONTRIBUTING.md
  lerna.json
  packages/cli/assets/cdk-wrapper/run.js
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/base-tsx/lambda.tsx
  packages/cli/test/config-esbuildconfig-invalid/config-esbuildconfig-invalid.test.js
  packages/cli/test/config-esbuildconfig-invalid/esbuild-config.js
  packages/cli/test/config-esbuildconfig-invalid/sst.json
  packages/cli/test/config-esbuildconfig-non-plugins/config-esbuildconfig-non-plugins.test.js
  packages/cli/test/config-esbuildconfig-non-plugins/esbuild-config.js
  packages/cli/test/config-esbuildconfig-non-plugins/sst.json
  packages/cli/test/config-esbuildconfig-not-found/sst.json
  packages/cli/test/config-esbuildconfig-not-set/esbuild-config.js
  packages/cli/test/config-esbuildconfig-not-set/lib/index.ts
  packages/cli/test/config-esbuildconfig-not-set/sst.json
  packages/cli/test/config-esbuildconfig/esbuild-config.js
  packages/cli/test/config-esbuildconfig/lib/index.ts
  packages/cli/test/config-esbuildconfig/sst.json
  packages/cli/test/nodejs-build-bundle-esbuildconfig/esbuild-config.js
  packages/cli/test/nodejs-build-bundle-esbuildconfig/lib/index.ts
  packages/cli/test/nodejs-handler-relative-path/nodejs-handler-relative-path/lambda.js
  packages/cli/test/playground/lib/api-stack.ts
  packages/cli/test/playground/lib/eventbus-stack.ts
  packages/cli/test/playground/src/lambdatsx.tsx
  packages/cli/test/playground/src/sites/jekyll-site/_config.yml
  packages/cli/test/playground/src/sites/jekyll-site/_posts/2021-06-06-welcome-to-jekyll.markdown
  packages/cli/test/playground/src/sites/jekyll-site/about.markdown
  packages/resources/assets/StaticSite/archiver.js
  packages/resources/assets/StaticSite/stub/index.html
  packages/resources/src/Api.ts
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/src/ApolloApi.ts
  packages/resources/src/Bucket.ts
  packages/resources/src/EventBus.ts
  packages/resources/src/util/construct.ts
  packages/resources/src/util/permission.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApolloApi.test.ts
  packages/resources/test/Bucket.test.ts
  packages/resources/test/EventBus.test.ts
  packages/resources/test/Function.test.ts
  packages/resources/test/ReactStaticSite.test.ts
  packages/resources/test/Stack.test.ts
  packages/resources/test/lambda-jsx.jsx
  packages/static-site-env/bin/scripts.js
  packages/static-site-env/test/sst-app-not-exist/sst-app-not-exist.test.js
Labels: internal

#644 Queue: Append .fifo to queue name when fifo is true
  packages/resources/src/Queue.ts
  packages/resources/test/Queue.test.ts
Labels: bug

#646 Fix lint warnings
  .eslintrc.json
  packages/resources/test/Function.test.ts
Labels: skip changelog

#649 Support typescript in @serverless-stack/core
  package.json
  packages/core/package.json
  packages/core/src/cancelablePromise.js
  packages/core/src/errorHelpers.js
  packages/core/src/index.js
  packages/core/src/logger.js
  packages/core/tsconfig.json
  yarn.lock
Labels: skip changelog

#651 Extract out environment loader into its own module
  packages/cli/assets/cdk-wrapper/run.js
  packages/cli/assets/debug-stack/bin/index.js
  packages/cli/package.json
  packages/cli/scripts/test.js
  packages/core/package.json
  packages/core/src/index.js
  packages/core/src/util/environment.ts
  packages/core/src/util/index.ts
  packages/core/src/util/paths.ts
  packages/core/tsconfig.json
  yarn.lock
Labels: skip changelog

#655 Support disabling local development feature
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
Labels: enhancement

#622 Honor a hostedZone construct if given as props
  packages/resources/src/StaticSite.ts
  packages/resources/test/StaticSite.test.ts
Labels: bug

#659 Reorganizing the permissions related docs
  www/docs/constructs/Api.md
  www/docs/constructs/ApiGatewayV1Api.md
  www/docs/constructs/AppSyncApi.md
  www/docs/constructs/Auth.md
  www/docs/constructs/Bucket.md
  www/docs/constructs/Cron.md
  www/docs/constructs/EventBus.md
  www/docs/constructs/Function.md
  www/docs/constructs/KinesisStream.md
  www/docs/constructs/Queue.md
  www/docs/constructs/Table.md
  www/docs/constructs/Topic.md
  www/docs/constructs/WebSocketApi.md
  www/docs/util/Permissions.md
Labels: documentation

#660 Fix static site looking for build directory when skipping build
  packages/resources/src/StaticSite.ts
  packages/resources/test/StaticSite.test.ts
Labels: bug

#663 Rename localDevelopment to enableLiveDev and add documentation
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/Function.md
Labels: enhancement

#670 Fix for copyFiles because outCode does not reliably return relative path
  packages/resources/src/Function.ts
Labels: bug

#683 ApolloApi: add serverFunction property
  packages/resources/src/ApolloApi.ts
  packages/resources/test/ApolloApi.test.ts
  www/docs/constructs/ApolloApi.md
Labels: enhancement

#685 Deprecate Node.js 10
  .github/workflows/ci.yml
Labels: enhancement

#686 Fix: dotenv does not accept false as valid value to turn off debugging
  packages/core/src/util/environment.ts
Labels: bug

#688 Single tsc watcher at root + autobuild core on yarn install
  package.json
  packages/core/package.json
  packages/resources/package.json
  packages/resources/tsconfig.json
  tsconfig.json
Labels: skip changelog

#692 Function: support F# .NET runtime
  README.md
  packages/cli/scripts/util/LambdaWatcherState.js
  packages/cli/test/base-dotnet/lib/index.js
  packages/cli/test/base-dotnet/src/CsharpFunction/CsharpFunction.csproj
  packages/cli/test/base-dotnet/src/CsharpFunction/Function.cs
  packages/cli/test/base-dotnet/src/FsharpFunction/FsharpFunction.fsproj
  packages/cli/test/base-dotnet/src/FsharpFunction/Handler.fs
  packages/cli/test/lambda-watcher-state/lambda-watcher-state.test.js
  packages/create-serverless-stack/README.md
  packages/create-serverless-stack/bin/index.js
  packages/create-serverless-stack/templates/fsharp/.env
  packages/create-serverless-stack/templates/fsharp/.template.gitignore
  packages/create-serverless-stack/templates/fsharp/README.template.md
  packages/create-serverless-stack/templates/fsharp/lib/%stack-name.PascalCased%.template.js
  packages/create-serverless-stack/templates/fsharp/lib/index.template.js
  packages/create-serverless-stack/templates/fsharp/package.template.json
  packages/create-serverless-stack/templates/fsharp/src/Api/Api.fsproj
  packages/create-serverless-stack/templates/fsharp/src/Api/Handlers.fs
  packages/create-serverless-stack/templates/fsharp/sst.template.json
  packages/create-serverless-stack/templates/fsharp/test/%stack-name.PascalCased%.test.template.js
  www/docs/constructs/Function.md
  www/docs/installation.md
  www/docs/packages/create-serverless-stack.md
  www/docusaurus.config.js
Labels: enhancement

#538 AppSyncApi: support multiple schemas
  packages/resources/package.json
  packages/resources/src/AppSyncApi.ts
  packages/resources/test/AppSyncApi.test.ts
  packages/resources/test/appsync/schema.graphql
  packages/resources/test/appsync/schema2.graphql
  packages/resources/test/schema.graphql
  www/docs/constructs/AppSyncApi.md
  yarn.lock
Labels: enhancement

#695 Update CDK version to 1.114
  packages/cli/package.json
  packages/cli/test/base-dotnet/package.json
  packages/cli/test/base-go/package.json
  packages/cli/test/base-python/package.json
  packages/cli/test/base-ts/package.json
  packages/cli/test/base-tsx/package.json
  packages/cli/test/base/package.json
  packages/cli/test/config-main-js/package.json
  packages/cli/test/config-main-ts/package.json
  packages/cli/test/config/package.json
  packages/cli/test/context/package.json
  packages/cli/test/dotenv/package.json
  packages/cli/test/dotnet-bootstrap/package.json
  packages/cli/test/dotnet-build/package.json
  packages/cli/test/eslint-lambda-override-eslintrc/package.json
  packages/cli/test/go-build/package.json
  packages/cli/test/is-local/package.json
  packages/cli/test/jest-ts/package.json
  packages/cli/test/jest/package.json
  packages/cli/test/lambda-override-tsconfig/package.json
  packages/cli/test/lambda-watcher-state/package.json
  packages/cli/test/nodejs-bootstrap/package.json
  packages/cli/test/nodejs-build-bundle-copyfiles/package.json
  packages/cli/test/nodejs-build-bundle-esbuildconfig/package.json
  packages/cli/test/nodejs-build-bundle-externalmodules/package.json
  packages/cli/test/nodejs-build-bundle-loader/package.json
  packages/cli/test/nodejs-build-bundle-no-srcpath/package.json
  packages/cli/test/nodejs-build-bundle-nodemodules/package.json
  packages/cli/test/nodejs-build-bundle-srcpath/package.json
  packages/cli/test/nodejs-build-no-bundle-no-srcpath/package.json
  packages/cli/test/nodejs-build-no-bundle-srcpath/package.json
  packages/cli/test/nodejs-handler-filename-with-dot/package.json
  packages/cli/test/nodejs-handler-relative-path/package.json
  packages/cli/test/playground/package.json
  packages/cli/test/remove/package.json
  packages/cli/test/rest-api-auth-cognito/package.json
  packages/cli/test/stack-no-prefix/package.json
  packages/cli/test/start-base/package.json
  packages/cli/test/start-demo/package.json
  packages/cli/test/start-guide/package.json
  packages/cli/test/start-handler-sync-async-cases/package.json
  packages/cli/test/start-no-src-path/package.json
  packages/cli/test/template-app-ts/package.json
  packages/cli/test/template-app/package.json
  packages/core/package.json
  packages/resources/package.json
  yarn.lock
Labels: enhancement

#698 Function: remove trailing slash from srcPath
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
Labels: skip changelog

#702 CLI: Add update command to update SST + related CDK versions
  packages/cli/bin/scripts.js
  packages/cli/test/update/.gitignore
  packages/cli/test/update/package.json
  packages/cli/test/update/sst.json
  packages/cli/test/update/update.test.js
  packages/core/src/index.js
  packages/core/src/update/index.ts
  packages/core/src/update/update.ts
  www/docs/packages/cli.md
Labels: enhancement

#703 Update esbuild to 0.12.17
  packages/cli/package.json
  packages/cli/scripts/start.js
  packages/cli/scripts/util/LambdaWatcherState.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/resources/assets/nodejs/esbuild.js
  packages/resources/package.json
  packages/resources/src/util/nodeBuilder.ts
  yarn.lock
Labels: enhancement

#705 CLI: Make update more resilient for various configurations
  packages/cli/test/update/package.json
  packages/cli/test/update/update.test.js
  packages/core/src/update/update.ts
Labels: bug

#708 Function: Throw useful error when copyFiles target does not exist
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
Labels: bug

#711 Tweaking update command copy
  packages/cli/bin/scripts.js
  www/docs/packages/cli.md
Labels: documentation

#712 Examples: Api with Lambda authorizers
  examples/README.md
  examples/api-auth-lambda-authorizer-iam-response/.gitignore
  examples/api-auth-lambda-authorizer-iam-response/README.md
  examples/api-auth-lambda-authorizer-iam-response/lib/MyStack.js
  examples/api-auth-lambda-authorizer-iam-response/lib/index.js
  examples/api-auth-lambda-authorizer-iam-response/package.json
  examples/api-auth-lambda-authorizer-iam-response/src/authorizer.js
  examples/api-auth-lambda-authorizer-iam-response/src/private.js
  examples/api-auth-lambda-authorizer-iam-response/src/public.js
  examples/api-auth-lambda-authorizer-iam-response/sst.json
  examples/api-auth-lambda-authorizer-simple-response/.gitignore
  examples/api-auth-lambda-authorizer-simple-response/README.md
  examples/api-auth-lambda-authorizer-simple-response/lib/MyStack.js
  examples/api-auth-lambda-authorizer-simple-response/lib/index.js
  examples/api-auth-lambda-authorizer-simple-response/package.json
  examples/api-auth-lambda-authorizer-simple-response/src/authorizer.js
  examples/api-auth-lambda-authorizer-simple-response/src/private.js
  examples/api-auth-lambda-authorizer-simple-response/src/public.js
  examples/api-auth-lambda-authorizer-simple-response/sst.json
Labels: documentation

#713 Example: Api in Python
  examples/README.md
  examples/rest-api-python/.gitignore
  examples/rest-api-python/Pipfile
  examples/rest-api-python/README.md
  examples/rest-api-python/lib/MyStack.js
  examples/rest-api-python/lib/index.js
  examples/rest-api-python/package-lock.json
  examples/rest-api-python/package.json
  examples/rest-api-python/src/Pipfile
  examples/rest-api-python/src/Pipfile.lock
  examples/rest-api-python/src/db/notes.py
  examples/rest-api-python/src/get.py
  examples/rest-api-python/src/list.py
  examples/rest-api-python/src/requirements.txt
  examples/rest-api-python/src/update.py
  examples/rest-api-python/sst.json
  examples/rest-api-python/test/MyStack.test.js
Labels: documentation

#715 CLI: Hide update command packager output behind verbose flag
  packages/cli/bin/scripts.js
  packages/cli/test/update/update.test.js
  packages/core/src/update/update.ts
Labels: enhancement

#707 CLI: Increase payload limit for Lambda Runtime Server
  packages/cli/scripts/util/LambdaRuntimeServer.js
Labels: bug

#722 sst start: handler function returning function crashes
  packages/cli/lib/object.js
  packages/cli/scripts/util/bootstrap.js
Labels: bug

#724 sst start: print error object with full depth
  packages/cli/scripts/start.js
Labels: enhancement

#717 Function: infer copyFiles destination from source path
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
Labels: enhancement

#699 StaticSite: Add support for external domains
  packages/resources/src/StaticSite.ts
  packages/resources/test/StaticSite.test.ts
  www/docs/constructs/ReactStaticSite.md
  www/docs/constructs/StaticSite.md
Labels: enhancement

#718 App: Support setting defaultRemovalPolicy
  packages/resources/src/App.ts
  packages/resources/test/App.test.ts
  www/docs/constructs/App.md
Labels: enhancement

#731 CLI: Scan recursively to figure out if project is using yarn
  packages/cli/bin/scripts.js
  packages/cli/test/add-cdk/add-cdk.test.js
  packages/core/src/index.js
  packages/core/src/packager/index.ts
  packages/core/src/packager/packager.ts
  packages/core/src/update/update.ts
Labels: bug

#743 Disable version reporting to skip unnecessary CF updates
  packages/core/src/index.js
Labels: enhancement

#744 Fix issue with inconsistent updates to functions
  packages/resources/src/Function.ts
Labels: bug

#746 Adding example for default removal policy
  www/docs/constructs/App.md
Labels: documentation

#764 Function: Python functions in different stacks cannot share the same srcPath
  packages/resources/src/Function.ts
  packages/resources/src/util/dotnetBuilder.ts
  packages/resources/src/util/pythonBuilder.ts
Labels: bug

#765 Function: do not reinstall bundle nodeModules
  packages/cli/test/nodejs-build-bundle-nodemodules/lib/index.js
  packages/cli/test/nodejs-build-bundle-nodemodules/nodejs-build-bundle-nodemodules.test.js
  packages/cli/test/nodejs-build-bundle-nodemodules/src/lambda2.js
  packages/resources/src/util/nodeBuilder.ts
Labels: enhancement

#767 Api: support route throttling
  packages/resources/src/Api.ts
  packages/resources/test/Api.test.ts
Labels: enhancement

#768 sst start: fix --outputs-file option not working
  packages/cli/scripts/deploy.js
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/helpers/run-start-command.js
  packages/cli/test/start-base/start-base.test.js
Labels: bug

#769 Auth: add cognitoIdentityPoolId property
  packages/resources/src/Auth.ts
  packages/resources/test/Auth.test.ts
Labels: enhancement

#770 Making Windows compatible
  packages/core/src/packager/packager.ts
Labels: bug
