Repository serverless-stack/sst, pull requests merged in 2021-01, with the labels that each got.

#39 Remove entry from sst.Function construct
  lerna.json
  packages/cli/scripts/start.js
  packages/cli/test/jest/lib/mystack.js
  packages/cli/test/lambda-override-eslintrc/lib/index.js
  packages/cli/test/start-base/lib/index.js
  packages/cli/test/start-base/sst.json
  packages/cli/test/start-base/start-base.test.js
  packages/cli/test/start-no-src-path/lib/index.js
  packages/cli/test/start-no-src-path/sst.json
  packages/cli/test/start-no-src-path/start-no-src-path.test.js
  packages/resources/lambda/stub/index.js
  packages/resources/src/App.ts
  packages/resources/src/Function.ts
  packages/resources/src/util/builder.ts
Labels: breaking

#42 Bug fixes
  packages/cli/scripts/deploy.js
  packages/cli/scripts/remove.js
Labels: bug

#40 Setting up docs
  README.md
  packages/cli/README.md
  packages/core/README.md
  packages/create-serverless-stack/README.md
  packages/resources/README.md
  www/.gitignore
  www/babel.config.js
  www/config.js
  www/docs/about.md
  www/docs/background.md
  www/docs/deploying-your-app.md
  www/docs/installation.md
  www/docs/known-issues.md
  www/docs/migrating-from-cdk.md
  www/docs/packages/cli.md
  www/docs/packages/create-serverless-stack.md
  www/docs/packages/resources.md
  www/docs/working-locally.md
  www/docusaurus.config.js
  www/package.json
  www/sidebars.js
  www/src/css/custom.css
  www/static/.nojekyll
  www/static/img/favicon.ico
  www/static/img/logo.svg
  www/yarn.lock
Labels: documentation

#47 Fixing broken link in docs
  www/docs/about.md
Labels: documentation

#50 Resolve paths to eslint and tsc in Yarn workspaces
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/add-cdk/package.json
  packages/cli/test/base-ts/package.json
  packages/cli/test/base/package.json
  packages/cli/test/cdk-command/package.json
  packages/cli/test/config-invalid/package.json
  packages/cli/test/config-no-name/package.json
  packages/cli/test/config-not-found/package.json
  packages/cli/test/config/package.json
  packages/cli/test/context/package.json
  packages/cli/test/eslint-ignore-rule/package.json
  packages/cli/test/eslint-ignore/package.json
  packages/cli/test/eslint-ts/package.json
  packages/cli/test/eslint/package.json
  packages/cli/test/handler-function-not-found/package.json
  packages/cli/test/handler-not-found/package.json
  packages/cli/test/helpers/copy-symlinks.js
  packages/cli/test/jest-ts/package.json
  packages/cli/test/jest/package.json
  packages/cli/test/lambda-override-eslintrc/package.json
  packages/cli/test/lambda-override-tsconfig/lib/index.ts
  packages/cli/test/lambda-override-tsconfig/package.json
  packages/cli/test/mismatched-cdk-versions/package.json
  packages/cli/test/stack-no-prefix/package.json
  packages/cli/test/stack-set-env/package.json
  packages/cli/test/start-base/package.json
  packages/cli/test/start-guide/package.json
  packages/cli/test/start-no-src-path/package.json
  packages/resources/src/App.ts
  packages/resources/src/util/builder.ts
  yarn.lock
Labels: bug

#51 Updating sst.Functions docs
  packages/resources/src/Function.ts
  www/docs/packages/resources.md
Labels: documentation

#53 Debug logs not flushed to file on process.exit
  packages/cli/scripts/util/cdkHelpers.js
Labels: bug

#54 Fixing sst.Function props in template
  packages/create-serverless-stack/templates/javascript/lib/%stack-name.PascalCased%.template.js
  packages/create-serverless-stack/templates/typescript/lib/%stack-name.PascalCased%.template.ts
  packages/resources/src/Function.ts
Labels: bug

#57 Handling error cases for eslint and tsc
  README.md
  packages/cli/assets/cdk-wrapper/.eslintrc.internal.js
  packages/cli/scripts/util/cdkHelpers.js
Labels: bug

#58 Fix logs not flushed to file on process.exit
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/core/index.js
  packages/core/logger.js
  packages/core/package.json
  yarn.lock
Labels: bug

#60 Moving lambda to src dir in template
  packages/create-serverless-stack/templates/javascript/lib/%stack-name.PascalCased%.template.js
  packages/create-serverless-stack/templates/javascript/src/lambda.js
  packages/create-serverless-stack/templates/typescript/lib/%stack-name.PascalCased%.template.ts
  packages/create-serverless-stack/templates/typescript/src/lambda.ts
  packages/resources/src/util/builder.ts
Labels: enhancement

#62 Adding DocSearch to docs
  www/docusaurus.config.js
  www/src/css/custom.css
Labels: documentation

#61 Applying default eslint env
  packages/cli/assets/cdk-wrapper/eslint.js
Labels: enhancement

#64 Fix error message if handler is not found for `sst start`
  packages/cli/assets/lambda-invoke/bootstrap.js
Labels: bug

#49 Implementing Api construct
  README.md
  package.json
  packages/cli/test/start-base/lib/index.js
  packages/cli/test/start-base/package.json
  packages/cli/test/start-guide/lib/ApiStack.js
  packages/cli/test/start-guide/lib/index.js
  packages/core/logger.js
  packages/create-serverless-stack/templates/javascript/lib/%stack-name.PascalCased%.template.js
  packages/create-serverless-stack/templates/javascript/package.template.json
  packages/create-serverless-stack/templates/typescript/lib/%stack-name.PascalCased%.template.ts
  packages/create-serverless-stack/templates/typescript/package.template.json
  packages/resources/.build/.esbuild.test-lambda-handler.json
  packages/resources/.build/lambda.js
  packages/resources/.build/lambda.js.map
  packages/resources/.gitignore
  packages/resources/jest.config.js
  packages/resources/package.json
  packages/resources/src/Api.ts
  packages/resources/src/App.ts
  packages/resources/src/Function.ts
  packages/resources/src/NodejsFunction.ts
  packages/resources/src/index.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/App.test.ts
  packages/resources/test/Function.test.ts
  packages/resources/test/helpers.ts
  packages/resources/test/lambda.js
  www/docs/about.md
  www/docs/constructs/api.md
  www/docs/constructs/app.md
  www/docs/constructs/function.md
  www/docs/constructs/stack.md
  www/docs/live-lambda-development.md
  www/docs/packages/cli.md
  www/docs/packages/resources.md
  www/docusaurus.config.js
  www/sidebars.js
Labels: enhancement

#70 Fixing paths to detect TypeScript bin in Windows
  packages/cli/scripts/util/cdkHelpers.js
  packages/resources/src/App.ts
Labels: bug

#68 Forcing ESLint to look at own node_modules to resolve plugins
  packages/cli/scripts/util/cdkHelpers.js
Labels: bug

#69 Ignoring node_modules for ESLint CDK code
  packages/cli/scripts/util/cdkHelpers.js
Labels: bug

#72 Set the srcpath for lambda eslint process to handle plugin resolution
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/resources/.npmignore
  packages/resources/src/App.ts
Labels: bug

#74 Adding missing dependencies for the Api construct
  package.json
  packages/cli/package.json
  packages/cli/test/template-app-ts/lib/MyStack.ts
  packages/cli/test/template-app-ts/lib/index.ts
  packages/cli/test/template-app-ts/package.json
  packages/cli/test/template-app-ts/src/lambda.ts
  packages/cli/test/template-app-ts/sst.json
  packages/cli/test/template-app-ts/template-app-ts.test.js
  packages/cli/test/template-app-ts/test/MyStack.test.ts
  packages/cli/test/template-app-ts/tsconfig.json
  packages/cli/test/template-app/lib/MyStack.js
  packages/cli/test/template-app/lib/index.js
  packages/cli/test/template-app/package.json
  packages/cli/test/template-app/src/lambda.js
  packages/cli/test/template-app/sst.json
  packages/cli/test/template-app/template-app.test.js
  packages/cli/test/template-app/test/MyStack.test.js
  packages/resources/package.json
  yarn.lock
Labels: bug
