Repository serverless-stack/sst, pull requests merged in 2021-09, with the labels that each got.

#748 Api: Support passing stages
  packages/resources/src/Api.ts
  packages/resources/src/util/apiGatewayV2AccessLog.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/WebSocketApi.test.ts
Labels: enhancement

#772 Prompt for default stage name
  .eslintrc.json
  packages/cli/.gitignore
  packages/cli/bin/scripts.js
  packages/cli/scripts/start.js
  packages/core/src/index.js
  packages/core/src/state/index.ts
  packages/core/src/state/state.ts
  packages/create-serverless-stack/templates/csharp/.template.gitignore
  packages/create-serverless-stack/templates/fsharp/.template.gitignore
  packages/create-serverless-stack/templates/go/.template.gitignore
  packages/create-serverless-stack/templates/javascript/.template.gitignore
  packages/create-serverless-stack/templates/python/.template.gitignore
  packages/create-serverless-stack/templates/typescript/.template.gitignore
  www/docs/constructs/App.md
  www/docs/deploying-your-app.md
  www/docs/packages/cli.md
Labels: enhancement

#786 Script: construct for running scripts during deployment
  .eslintrc.json
  README.md
  packages/cli/assets/cdk-wrapper/run.js
  packages/cli/scripts/start.js
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/lib/script-stack.ts
  packages/cli/test/playground/src/script.js
  packages/resources/src/Api.ts
  packages/resources/src/App.ts
  packages/resources/src/Function.ts
  packages/resources/src/Script.ts
  packages/resources/src/Script/cfn-response.ts
  packages/resources/src/Script/index.ts
  packages/resources/src/Script/outbound.ts
  packages/resources/src/Script/util.ts
  packages/resources/src/index.ts
  packages/resources/test/Script.test.ts
  www/docs/constructs/Script.md
  www/sidebars.js
Labels: enhancement

#796 Bucket: Do not recreate deletion function if it exists
  packages/resources/src/App.ts
Labels: bug

#799 Function: Remove readonly for exported types
  packages/resources/src/Function.ts
Labels: internal

#801 CLI: Clear cache when updating package version
  packages/core/src/update/update.ts
Labels: bug

#802 Tweak copy and docs for default stage option
  packages/cli/bin/scripts.js
  www/docs/deploying-your-app.md
  www/docs/installation.md
  www/docs/working-locally.md
Labels: documentation

#789 Function: New api for default props
  packages/resources/src/App.ts
  packages/resources/src/Function.ts
  packages/resources/src/Stack.ts
  packages/resources/test/Function.test.ts
  packages/static-site-env/test/sst-env-outputs-not-found/sst-env-outputs-not-found.test.js
  www/docs/constructs/App.md
  www/docs/constructs/Stack.md
Labels: enhancement

#804 Clone examples with create-serverless-stack
  packages/create-serverless-stack/bin/index.js
  packages/create-serverless-stack/package.json
  yarn.lock
Labels: enhancement

#809 Add ARN property to API stack
  packages/resources/src/Api.ts
  packages/resources/test/Api.test.ts
Labels: enhancement

#814 Updating example READMEs with `--example` option
  examples/README.md
  examples/api-auth-auth0/README.md
  examples/api-auth-cognito/README.md
  examples/api-auth-facebook/README.md
  examples/api-auth-google/README.md
  examples/api-auth-jwt-auth0/README.md
  examples/api-auth-jwt-cognito-user-pool/README.md
  examples/api-auth-lambda-authorizer-iam-response/README.md
  examples/api-auth-lambda-authorizer-simple-response/README.md
  examples/api-auth-twitter/README.md
  examples/bucket-image-resize/README.md
  examples/cron-job/README.md
  examples/crud-api-dynamodb/README.md
  examples/graphql-apollo/README.md
  examples/graphql-appsync/README.md
  examples/layer-chrome-aws-lambda/README.md
  examples/pub-sub/README.md
  examples/queue/README.md
  examples/react-app-auth-cognito/README.md
  examples/react-app/README.md
  examples/rest-api-csharp/README.md
  examples/rest-api-custom-domain/README.md
  examples/rest-api-dynamodb/README.md
  examples/rest-api-go/README.md
  examples/rest-api-mongodb/README.md
  examples/rest-api-postgresql/README.md
  examples/rest-api-python/README.md
  examples/rest-api-ts/README.md
  examples/rest-api/README.md
  examples/vscode/README.md
  examples/websocket/README.md
Labels: documentation

#818 Editing docs for default function props change
  packages/resources/src/App.ts
  packages/resources/src/Stack.ts
  www/docs/constructs/App.md
  www/docs/constructs/Stack.md
Labels: documentation

#820 StaticSitic: Add 'disablePlaceholder' boolean to StaticSite props
  packages/resources/src/StaticSite.ts
Labels: enhancement

#824 Typescript example
  examples/typescript/.gitignore
  examples/typescript/README.md
  examples/typescript/backend/core/index.ts
  examples/typescript/backend/core/sample/index.ts
  examples/typescript/backend/core/sample/sample.ts
  examples/typescript/backend/jest.config.js
  examples/typescript/backend/package.json
  examples/typescript/backend/scripts/example.ts
  examples/typescript/backend/services/sample/index.ts
  examples/typescript/backend/test/core/sample.test.ts
  examples/typescript/backend/tsconfig.json
  examples/typescript/package.json
  examples/typescript/sst.json
  examples/typescript/sst/MyStack.ts
  examples/typescript/sst/index.ts
  examples/typescript/tsconfig.json
  examples/typescript/yarn.lock
Labels: documentation

#825 NextjsSite: use placeholder function when the api, image or regenerate features are not used
  packages/resources/src/NextjsSite.ts
  packages/resources/src/util/builder.ts
  packages/resources/test/NextjsSite.test.ts
  packages/resources/test/nextjs-site-minimal-features/.gitignore
  packages/resources/test/nextjs-site-minimal-features/next.config.js
  packages/resources/test/nextjs-site-minimal-features/package-lock.json
  packages/resources/test/nextjs-site-minimal-features/package.json
  packages/resources/test/nextjs-site-minimal-features/pages/index.js
  packages/resources/test/nextjs-site-minimal-features/public/favicon.ico
  www/docs/constructs/NextjsSite.md
Labels: bug

#826 Fix typo in ReactStaticSite.md
  www/docs/constructs/ReactStaticSite.md
Labels: documentation

#830 NextjsSite: support environments in dynamically generated pages
  packages/cli/test/playground/src/sites/nextjs/pages/api/hello.js
  packages/cli/test/playground/src/sites/nextjs/pages/csr.js
  packages/cli/test/playground/src/sites/nextjs/pages/env.js
  packages/cli/test/playground/src/sites/nextjs/pages/index.js
  packages/cli/test/playground/src/sites/nextjs/pages/isr.js
  packages/cli/test/playground/src/sites/nextjs/pages/posts/[id].js
  packages/cli/test/playground/src/sites/nextjs/pages/ssg-fallback-true/[id].js
  packages/cli/test/playground/src/sites/nextjs/pages/ssr.js
  packages/resources/assets/NextjsSite/custom-resource/lambda-code-updater.py
  packages/resources/assets/NextjsSite/custom-resource/s3-handler.py
  packages/resources/src/NextjsSite.ts
  packages/resources/test/NextjsSite.test.ts
  packages/resources/test/nextjs-site/pages/env.js
  www/docs/constructs/NextjsSite.md
Labels: bug

#840 Topic: add tests and docs for FIFO topic
  packages/resources/test/Topic.test.ts
  www/docs/constructs/Topic.md
Labels: skip changelog

#833 StaticSite: Extended boto3 client timeout
  packages/resources/assets/NextjsSite/custom-resource/s3-handler.py
  packages/resources/assets/StaticSite/custom-resource/index.py
Labels: bug

#841 NextjsSite: support environments in SSG prefetched data
  packages/cli/test/playground/src/sites/nextjs/pages/posts/[id].js
  packages/resources/src/NextjsSite.ts
  packages/resources/test/NextjsSite.test.ts
Labels: bug

#846 Updating Next.js docs
  examples/nextjs-app/frontend/pages/api/count.js
  examples/nextjs-app/lib/MyStack.js
  packages/static-site-env/README.md
  www/docs/constructs/NextjsSite.md
  www/docs/packages/static-site-env.md
Labels: documentation

#842 Trim stage input to avoid empty stage names
  packages/cli/bin/scripts.js
  packages/core/src/state/state.ts
Labels: bug

#844 #775 WebSocketApi: support Lambda authorizer
  packages/resources/src/Api.ts
  packages/resources/src/WebSocketApi.ts
  packages/resources/test/WebSocketApi.test.ts
Labels: enhancement

#848 Fix typo in NextjsSite docs
  www/docs/constructs/NextjsSite.md
Labels: documentation

#836 Prisma example
  examples/README.md
  examples/prisma/.gitignore
  examples/prisma/README.md
  examples/prisma/package.json
  examples/prisma/prisma/migrations/20210917000038_first/migration.sql
  examples/prisma/prisma/migrations/migration_lock.toml
  examples/prisma/prisma/schema.prisma
  examples/prisma/src/index.ts
  examples/prisma/sst.json
  examples/prisma/stacks/index.ts
  examples/prisma/tsconfig.json
  examples/prisma/yarn.lock
  packages/resources/src/App.ts
  packages/resources/src/Stack.ts
Labels: documentation

#852 sst deploy: build errors do not terminate the command
  packages/cli/assets/cdk-wrapper/run.js
Labels: bug

#853 NextjsSite: support non-public environment in server side rendering
  packages/cli/test/playground/lib/nextjs-site-stack.ts
  packages/cli/test/playground/src/sites/nextjs/pages/api/hello.js
  packages/cli/test/playground/src/sites/nextjs/pages/csr.js
  packages/cli/test/playground/src/sites/nextjs/pages/isr.js
  packages/cli/test/playground/src/sites/nextjs/pages/posts/[id].js
  packages/cli/test/playground/src/sites/nextjs/pages/ssr.js
  packages/resources/package.json
  packages/resources/src/NextjsSite.ts
  packages/resources/test/NextjsSite.test.ts
  yarn.lock
Labels: bug

#807 Allow keepNames esbuild config option
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/nodejs-build-bundle-esbuildconfig/lib/index.ts
  packages/resources/assets/nodejs/esbuild.js
  packages/resources/src/Function.ts
  packages/resources/src/util/nodeBuilder.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/Function.md
  www/docs/installation.md
Labels: enhancement

#822 Added documentation for monitoring services
  packages/resources/src/Stack.ts
  packages/resources/test/Stack.test.ts
  www/docs/constructs/Api.md
  www/docs/monitoring-your-app-in-prod.md
  www/sidebars.js
Labels: documentation

#843 Function: Preserve original path when bundling js
  packages/cli/test/nodejs-build-bundle-externalmodules/nodejs-build-bundle-externalmodules.test.js
  packages/cli/test/nodejs-build-bundle-no-srcpath/nodejs-build-bundle-no-srcpath.test.js
  packages/cli/test/nodejs-build-bundle-srcpath/nodejs-build-bundle-srcpath.test.js
  packages/cli/test/nodejs-build-no-bundle-srcpath/nodejs-build-no-bundle-srcpath.test.js
  packages/cli/test/nodejs-handler-relative-path/nodejs-handler-relative-path/lambda.js
  packages/cli/test/nodejs-handler-relative-path/nodejs-handler-relative-path/lambda.js.map
  packages/resources/.gitignore
  packages/resources/src/util/nodeBuilder.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
  packages/resources/test/ApolloApi.test.ts
  packages/resources/test/AppSyncApi.test.ts
  packages/resources/test/Auth.test.ts
  packages/resources/test/Bucket.test.ts
  packages/resources/test/Cron.test.ts
  packages/resources/test/EventBus.test.ts
  packages/resources/test/Function.test.ts
  packages/resources/test/KinesisStream.test.ts
  packages/resources/test/Queue.test.ts
  packages/resources/test/Script.test.ts
  packages/resources/test/Table.test.ts
  packages/resources/test/Topic.test.ts
  packages/resources/test/WebSocketApi.test.ts
  packages/resources/test/nested/lambda.js
Labels: enhancement

#858 Typescript update to 4.4.3
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/resources/package.json
  packages/resources/src/App.ts
  packages/resources/src/Script/cfn-response.ts
  yarn.lock
Labels: enhancement

#861 Docs for Stack getAllFunctions
  www/docs/constructs/Api.md
  www/docs/constructs/Stack.md
Labels: documentation

#863 SST Update: Read package.json manually instead of using require
  packages/core/src/update/update.ts
Labels: bug

#864 SST Update: Allow specifying version + do not require stage name
  packages/cli/bin/scripts.js
  packages/core/src/update/update.ts
Labels: enhancement

#865 Update docs for addDefaultFunctionLayers
  www/docs/constructs/App.md
  www/docs/constructs/Stack.md
  www/docs/monitoring-your-app-in-prod.md
Labels: documentation

#867 Editing Prisma example
  examples/README.md
  examples/prisma/README.md
  examples/prisma/stacks/index.ts
  packages/cli/test/playground/src/sites/nextjs/pages/api/preview.js
  packages/cli/test/playground/src/sites/nextjs/pages/ssg-preview/[id].js
  packages/static-site-env/README.md
Labels: documentation

#869 Docs on multiple developer setups
  www/docs/debugging-with-vscode.md
  www/docs/live-lambda-development.md
  www/docs/working-with-your-team.md
  www/sidebars.js
Labels: documentation
