Repository serverless-stack/sst, pull requests merged in 2021-02, with the labels that each got.

#79 Fixing zip-issue
  packages/cli/scripts/start.js
  packages/cli/test/build-bundle-no-srcpath/build-bundle-no-srcpath.test.js
  packages/cli/test/build-bundle-no-srcpath/lambda.js
  packages/cli/test/build-bundle-no-srcpath/lib/index.js
  packages/cli/test/build-bundle-no-srcpath/package.json
  packages/cli/test/build-bundle-no-srcpath/service/lambda.js
  packages/cli/test/build-bundle-no-srcpath/service/src/lambda.js
  packages/cli/test/build-bundle-no-srcpath/src/lambda.js
  packages/cli/test/build-bundle-no-srcpath/sst.json
  packages/cli/test/build-bundle-srcpath/build-bundle-srcpath.test.js
  packages/cli/test/build-bundle-srcpath/lambda.js
  packages/cli/test/build-bundle-srcpath/lib/index.js
  packages/cli/test/build-bundle-srcpath/package.json
  packages/cli/test/build-bundle-srcpath/service/lambda.js
  packages/cli/test/build-bundle-srcpath/service/src/lambda.js
  packages/cli/test/build-bundle-srcpath/src/lambda.js
  packages/cli/test/build-bundle-srcpath/sst.json
  packages/cli/test/build-no-bundle-no-srcpath/build-no-bundle-no-srcpath.test.js
  packages/cli/test/build-no-bundle-no-srcpath/lambda.js
  packages/cli/test/build-no-bundle-no-srcpath/lib/index.js
  packages/cli/test/build-no-bundle-no-srcpath/package.json
  packages/cli/test/build-no-bundle-no-srcpath/service/lambda.js
  packages/cli/test/build-no-bundle-no-srcpath/service/src/lambda.js
  packages/cli/test/build-no-bundle-no-srcpath/src/lambda.js
  packages/cli/test/build-no-bundle-no-srcpath/sst.json
  packages/cli/test/build-no-bundle-srcpath/build-no-bundle-srcpath.test.js
  packages/cli/test/build-no-bundle-srcpath/lambda.js
  packages/cli/test/build-no-bundle-srcpath/lib/index.js
  packages/cli/test/build-no-bundle-srcpath/package.json
  packages/cli/test/build-no-bundle-srcpath/service/lambda.js
  packages/cli/test/build-no-bundle-srcpath/service/src/lambda.js
  packages/cli/test/build-no-bundle-srcpath/src/lambda.js
  packages/cli/test/build-no-bundle-srcpath/sst.json
  packages/cli/test/start-base/start-base.test.js
  packages/resources/src/App.ts
  packages/resources/src/Function.ts
  packages/resources/src/util/builder.ts
  www/docs/constructs/function.md
Labels: bug

#75 For the npm run -- option add helper warning and docs
  packages/cli/bin/scripts.js
  www/docs/deploying-your-app.md
  www/docs/packages/cli.md
  www/docs/working-locally.md
Labels: enhancement

#76 Add Table, Topic, Queue and Cron Constructs
  packages/cli/test/start-guide/lib/ApiStack.js
  packages/cli/test/start-guide/lib/DynamoDBStack.js
  packages/cli/test/start-guide/lib/MiscStack.js
  packages/cli/test/start-guide/lib/index.js
  packages/cli/test/start-guide/services/misc/handler.js
  packages/cli/test/start-no-src-path/lib/index.js
  packages/resources/.build/.esbuild.test-lambda-handler.json
  packages/resources/.build/lambda.js
  packages/resources/.build/lambda.js.map
  packages/resources/.gitignore
  packages/resources/jest.config.js
  packages/resources/package.json
  packages/resources/src/Api.ts
  packages/resources/src/App.ts
  packages/resources/src/Cron.ts
  packages/resources/src/Function.ts
  packages/resources/src/Queue.ts
  packages/resources/src/Table.ts
  packages/resources/src/Topic.ts
  packages/resources/src/index.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/Cron.test.ts
  packages/resources/test/Function.test.ts
  packages/resources/test/Queue.test.ts
  packages/resources/test/Table.test.ts
  packages/resources/test/Topic.test.ts
  packages/resources/test/helpers.ts
  packages/resources/test/setup-tests.js
  www/docs/constructs/api.md
  www/docs/constructs/app.md
  www/docs/constructs/cron.md
  www/docs/constructs/function.md
  www/docs/constructs/queue.md
  www/docs/constructs/stack.md
  www/docs/constructs/table.md
  www/docs/constructs/topic.md
  www/docs/packages/resources.md
  www/sidebars.js
  yarn.lock
Labels: enhancement

#81 Adding FAQ and design principles to the docs
  README.md
  packages/cli/README.md
  www/config.js
  www/docs/about.md
  www/docs/constructs/cron.md
  www/docs/deploying-your-app.md
  www/docs/design-principles.md
  www/docs/faq.md
  www/docs/installation.md
  www/docs/migrating-from-cdk.md
  www/docs/packages/cli.md
  www/docs/packages/resources.md
  www/docs/working-locally.md
  www/sidebars.js
  www/src/css/custom.css
Labels: documentation

#88 Add the auth construct
  packages/cli/test/rest-api-auth-cognito/lib/MyStack.js
  packages/cli/test/rest-api-auth-cognito/lib/index.js
  packages/cli/test/rest-api-auth-cognito/package.json
  packages/cli/test/rest-api-auth-cognito/src/private.js
  packages/cli/test/rest-api-auth-cognito/src/public.js
  packages/cli/test/rest-api-auth-cognito/sst.json
  packages/cli/test/start-guide/lib/CognitoAuthRole.js
  packages/cli/test/start-guide/lib/CognitoStack.js
  packages/cli/test/start-guide/lib/DynamoDBStack.js
  packages/cli/test/start-guide/lib/MiscStack.js
  packages/cli/test/start-guide/lib/index.js
  packages/resources/package.json
  packages/resources/src/Api.ts
  packages/resources/src/Auth.ts
  packages/resources/src/Cron.ts
  packages/resources/src/Function.ts
  packages/resources/src/Queue.ts
  packages/resources/src/Table.ts
  packages/resources/src/Topic.ts
  packages/resources/src/index.ts
  packages/resources/src/util/permission.ts
  packages/resources/test/Auth.test.ts
  packages/resources/test/Function.test.ts
  packages/resources/test/Table.test.ts
  www/docs/constructs/api.md
  www/docs/constructs/auth.md
  www/docs/constructs/cron.md
  www/docs/constructs/function.md
  www/docs/constructs/queue.md
  www/docs/constructs/table.md
  www/docs/constructs/topic.md
  www/docs/design-principles.md
  www/docs/util/permissions.md
  www/sidebars.js
Labels: enhancement

#89 Updating README in templates
  packages/create-serverless-stack/templates/javascript/README.template.md
  packages/create-serverless-stack/templates/typescript/README.template.md
Labels: documentation

#90 Stub Lambda should not reconnect to websocket on error code 1006 ENOTFOUND
  packages/resources/lambda/stub/index.js
Labels: bug

#96 Remove unused rest-api-auth-cognito test
  packages/cli/test/rest-api-auth-cognito/lib/MyStack.js
  packages/cli/test/rest-api-auth-cognito/lib/index.js
  packages/cli/test/rest-api-auth-cognito/src/private.js
  packages/cli/test/rest-api-auth-cognito/src/public.js
  packages/cli/test/rest-api-auth-cognito/sst.json
Labels: skip changelog

#98 Fix stub to handle debug stack removed error
  packages/resources/lambda/stub/index.js
Labels: bug

#99 Update cdk to v1.89.0
  packages/cli/package.json
  packages/cli/test/base-ts/package.json
  packages/cli/test/base/package.json
  packages/cli/test/build-bundle-no-srcpath/package.json
  packages/cli/test/build-bundle-srcpath/package.json
  packages/cli/test/build-no-bundle-no-srcpath/package.json
  packages/cli/test/build-no-bundle-srcpath/package.json
  packages/cli/test/config/package.json
  packages/cli/test/context/package.json
  packages/cli/test/jest-ts/package.json
  packages/cli/test/jest/package.json
  packages/cli/test/lambda-override-eslintrc/package.json
  packages/cli/test/lambda-override-tsconfig/package.json
  packages/cli/test/rest-api-auth-cognito/package.json
  packages/cli/test/stack-no-prefix/package.json
  packages/cli/test/start-base/package.json
  packages/cli/test/start-guide/package.json
  packages/cli/test/start-no-src-path/package.json
  packages/cli/test/template-app-ts/package.json
  packages/cli/test/template-app/package.json
  packages/core/package.json
  packages/resources/package.json
  yarn.lock
Labels: enhancement

#95 Add instructions on setting up VPN connection
  www/docs/live-lambda-development.md
Labels: documentation

#101 Fix callback waits for empty event loop
  packages/cli/assets/lambda-invoke/bootstrap.js
  packages/cli/test/start-demo/lib/index.js
  packages/cli/test/start-demo/package.json
  packages/cli/test/start-demo/src/api/api.ts
  packages/cli/test/start-demo/src/api/lib.ts
  packages/cli/test/start-demo/src/api/package.json
  packages/cli/test/start-demo/src/api/tsconfig.json
  packages/cli/test/start-demo/src/api/yarn.lock
  packages/cli/test/start-demo/src/sns/sub-folder/sns.js
  packages/cli/test/start-demo/sst.json
  packages/cli/test/start-handler-sync-async-cases/.DS_Store
  packages/cli/test/start-handler-sync-async-cases/api.js
  packages/cli/test/start-handler-sync-async-cases/lib/index.js
  packages/cli/test/start-handler-sync-async-cases/package.json
  packages/cli/test/start-handler-sync-async-cases/sst.json
  packages/resources/lambda/stub/index.js
  yarn.lock
Labels: bug

#105 Fix yarn start fails on windows 10 with EBADF error
  packages/cli/scripts/start.js
Labels: bug

#106 Fix GitHub actions for windows
  .github/workflows/ci.yml
  packages/cli/assets/lambda-invoke/bootstrap.js
  packages/cli/package.json
  packages/cli/scripts/start.js
  packages/cli/test/helpers/clear-build-output.js
  packages/cli/test/helpers/remove-node-modules.js
  packages/cli/test/start-base/start-base.test.js
  packages/create-serverless-stack/package.json
  packages/resources/bin/create-stub-zip.js
  packages/resources/package.json
  packages/resources/src/util/builder.ts
Labels: bug

#110 Support nodejs14.x Lambda runtime
  packages/resources/src/Function.ts
Labels: bug

#104 Support --outputs-file option for `sst deploy`
  packages/cli/bin/scripts.js
  packages/cli/scripts/deploy.js
  www/docs/packages/cli.md
Labels: enhancement

#114 Support ANY method for Api construct
  packages/resources/src/Api.ts
  packages/resources/test/Api.test.ts
Labels: bug

#115 Set esbuild target to "es2015"
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/resources/src/util/builder.ts
Labels: bug

#138 Add Auth0 support for `sst.Auth`
  packages/resources/src/Auth.ts
  packages/resources/test/Auth.test.ts
Labels: enhancement

#142 Pretty print error object when function invoke fails in sst start
  packages/cli/assets/lambda-invoke/bootstrap.js
  packages/cli/lib/serializeError.js
  packages/cli/scripts/start.js
Labels: bug

#141 Attach table and bucket permissions grants access to /* sub-resource
  packages/resources/package.json
  packages/resources/src/util/permission.ts
  packages/resources/test/Function.test.ts
Labels: bug

#146 Support custom domain for Api construct
  packages/resources/package.json
  packages/resources/src/Api.ts
  packages/resources/test/Api.test.ts
  www/docs/constructs/api.md
Labels: enhancement

#144 Fix attachPermission instanceof error
  packages/resources/src/util/permission.ts
  packages/resources/test/Function.test.ts
Labels: bug

#145 Set the esbuild target based on the current NodeJS runtime or Lambda runtime
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/resources/src/Function.ts
  packages/resources/src/util/builder.ts
Labels: bug

#147 Support JWT authorizer for Api construct
  packages/cli/package.json
  packages/cli/test/base-ts/package.json
  packages/cli/test/base/package.json
  packages/cli/test/build-bundle-no-srcpath/package.json
  packages/cli/test/build-bundle-srcpath/package.json
  packages/cli/test/build-no-bundle-no-srcpath/package.json
  packages/cli/test/build-no-bundle-srcpath/package.json
  packages/cli/test/config/package.json
  packages/cli/test/context/package.json
  packages/cli/test/eslint-lambda-override-eslintrc/package.json
  packages/cli/test/jest-ts/package.json
  packages/cli/test/jest/package.json
  packages/cli/test/lambda-override-tsconfig/package.json
  packages/cli/test/rest-api-auth-cognito/package.json
  packages/cli/test/stack-no-prefix/package.json
  packages/cli/test/start-base/package.json
  packages/cli/test/start-demo/package.json
  packages/cli/test/start-guide/package.json
  packages/cli/test/start-handler-sync-async-cases/package.json
  packages/cli/test/start-no-src-path/package.json
  packages/cli/test/template-app-ts/package.json
  packages/cli/test/template-app/package.json
  packages/core/package.json
  packages/resources/package.json
  packages/resources/src/Api.ts
  packages/resources/src/util/builder.ts
  packages/resources/test/Api.test.ts
  www/docs/constructs/api.md
  yarn.lock
Labels: enhancement

#149 Support context.getRemainingTimeInMillis() in live development
  packages/cli/assets/lambda-invoke/bootstrap.js
  packages/cli/scripts/start.js
Labels: bug

#152 Fix Api route authorizationType not removed when changed from AWS_IAM to NONE
  packages/resources/src/Api.ts
  packages/resources/test/Api.test.ts
Labels: bug

#154 Fixing tsc error if no tsconfig.json is found
  packages/cli/scripts/start.js
  packages/cli/test/lambda-override-tsconfig/src/tsconfig.json
  packages/cli/test/lambda-override-tsconfig/tsconfig.json
  packages/resources/src/App.ts
  www/docs/constructs/function.md
Labels: bug

#157 Fix permissions not supported error due to class name not matched
  packages/cli/assets/cdk-wrapper/run.js
  packages/resources/jest.config.js
  packages/resources/package.json
  packages/resources/src/App.ts
  packages/resources/src/descs.d.ts
  packages/resources/src/util/permission.ts
  packages/resources/test/Function.test.ts
  yarn.lock
Labels: bug

#159 Updating FAQ with more details
  www/docs/constructs/Api.md
  www/docs/constructs/App.md
  www/docs/constructs/Auth.md
  www/docs/constructs/Cron.md
  www/docs/constructs/Function.md
  www/docs/constructs/Queue.md
  www/docs/constructs/Stack.md
  www/docs/constructs/Table.md
  www/docs/constructs/Topic.md
  www/docs/deploying-your-app.md
  www/docs/design-principles.md
  www/docs/faq.md
  www/docs/installation.md
  www/docs/migrating-from-cdk.md
  www/docs/packages/resources.md
  www/docs/util/Permissions.md
Labels: documentation

#160 Support attaching invoke api permissions by passing in Api construct
  packages/resources/src/util/permission.ts
  packages/resources/test/Function.test.ts
Labels: enhancement
