Repository serverless-stack/sst, pull requests merged in 2021-06, with the labels that each got.

#407 SST equivalent of a SLS local invocation
  www/docs/migrating-from-serverless-framework.md
Labels: documentation

#409 Function: fix Python handler with multiple parts not set properly
  packages/resources/src/util/pythonBuilder.ts
Labels: bug

#411 sst start: remove Lambda response internal status from console
  packages/cli/scripts/start.js
Labels: skip changelog

#414 Tweaking copy in docs and helper
  packages/cli/bin/scripts.js
  www/docs/packages/cli.md
Labels: documentation

#419 StaticSite: add construct for static websites
  .eslintignore
  README.md
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/lib/static-site-stack.ts
  packages/cli/test/playground/lib/step-functions-stack.ts
  packages/cli/test/playground/package.json
  packages/cli/test/playground/src/sites/jekyll-site/.gitignore
  packages/cli/test/playground/src/sites/jekyll-site/404.html
  packages/cli/test/playground/src/sites/jekyll-site/Gemfile
  packages/cli/test/playground/src/sites/jekyll-site/Gemfile.lock
  packages/cli/test/playground/src/sites/jekyll-site/_config.yml
  packages/cli/test/playground/src/sites/jekyll-site/_posts/2021-06-06-welcome-to-jekyll.markdown
  packages/cli/test/playground/src/sites/jekyll-site/about.markdown
  packages/cli/test/playground/src/sites/jekyll-site/index.markdown
  packages/cli/test/playground/src/sites/react-app/.env
  packages/cli/test/playground/src/sites/react-app/.gitignore
  packages/cli/test/playground/src/sites/react-app/README.md
  packages/cli/test/playground/src/sites/react-app/package.json
  packages/cli/test/playground/src/sites/react-app/public/favicon.ico
  packages/cli/test/playground/src/sites/react-app/public/index.html
  packages/cli/test/playground/src/sites/react-app/public/logo192.png
  packages/cli/test/playground/src/sites/react-app/public/logo512.png
  packages/cli/test/playground/src/sites/react-app/public/manifest.json
  packages/cli/test/playground/src/sites/react-app/public/robots.txt
  packages/cli/test/playground/src/sites/react-app/src/App.css
  packages/cli/test/playground/src/sites/react-app/src/App.js
  packages/cli/test/playground/src/sites/react-app/src/index.css
  packages/cli/test/playground/src/sites/react-app/src/index.js
  packages/cli/test/playground/src/sites/react-app/src/logo.svg
  packages/cli/test/playground/src/sites/react-app/src/reportWebVitals.js
  packages/cli/test/playground/src/sites/react-app/src/setupTests.js
  packages/cli/test/playground/src/sites/react-app/yarn.lock
  packages/cli/test/playground/src/sites/website/error.html
  packages/cli/test/playground/src/sites/website/index.html
  packages/resources/package.json
  packages/resources/src/.ts
  packages/resources/src/StaticSite.ts
  packages/resources/src/index.ts
  packages/resources/test/StaticSite.test.ts
  packages/resources/test/site/error.html
  packages/resources/test/site/index.html
  www/docs/constructs/StaticSite.md
  www/sidebars.js
  yarn.lock
Labels: enhancement

#420 Bucket: expose bucketArn and bucketName props
  packages/resources/src/Bucket.ts
  packages/resources/test/Bucket.test.ts
  www/docs/constructs/Bucket.md
Labels: enhancement

#423 Replace dynamodbTable property with s3Bucket
  www/docs/constructs/StaticSite.md
Labels: skip changelog

#422 Function: merge inline layers with defaultFunctionProps
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/Api.md
  www/docs/constructs/ApiGatewayV1Api.md
  www/docs/constructs/App.md
  www/docs/constructs/Auth.md
  www/docs/constructs/KinesisStream.md
  www/docs/constructs/Table.md
  www/docs/constructs/Topic.md
  www/docs/constructs/WebSocketApi.md
Labels: enhancement

#425 StaticSite: create certificate in us-east-1 region
  packages/resources/src/StaticSite.ts
  packages/resources/test/StaticSite.test.ts
Labels: bug

#418 AppSyncApi: create resolver from the api not datasource
  packages/resources/src/AppSyncApi.ts
Labels: bug

#429 sst start: expose the app and the stack constructs in the debug stack
  packages/cli/assets/cdk-wrapper/run.js
  packages/cli/assets/debug-stack/bin/index.js
  packages/cli/assets/debug-stack/lib/DebugStack.js
  packages/cli/scripts/remove.js
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/playground/lib/index.ts
  packages/core/index.js
  packages/resources/src/App.ts
  packages/resources/src/DebugStack.ts
  packages/resources/src/index.ts
Labels: enhancement

#433 StaticSite: update typo tableName to bucketName
  www/docs/constructs/StaticSite.md
Labels: documentation

#438 Editing docs for recent changes
  www/docs/constructs/Api.md
  www/docs/constructs/Bucket.md
  www/docs/constructs/Table.md
  www/docs/debugging-with-vscode.md
  www/docs/live-lambda-development.md
  www/docs/packages/cli.md
Labels: documentation

#443 ApiGatewayV1Api: create Deployment resource when the REST Api is imported
  packages/cli/test/playground/lib/api-stack.ts
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
Labels: bug

#444 CLI: Add `--role-arn` option to take a CloudFormation execution role
  packages/cli/bin/scripts.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/core/index.js
  www/docs/packages/cli.md
Labels: enhancement

#449 Updating VS Code docs with the --increase-timeout option
  examples/vscode/.vscode/launch.json
  examples/vscode/lib/index.ts
  www/docs/debugging-with-vscode.md
  www/docs/live-lambda-development.md
Labels: documentation

#463 StaticSite: allow configuring the default behaviour
  packages/cli/test/playground/lib/api-stack.ts
  packages/cli/test/playground/lib/static-site-stack.ts
  packages/cli/test/playground/package.json
  packages/cli/test/playground/src/edge/lambda.js
  packages/core/index.js
  packages/resources/src/StaticSite.ts
  packages/resources/test/StaticSite.test.ts
  www/docs/constructs/StaticSite.md
Labels: enhancement

#465 Api: support setting domain to an SSM value
  packages/cli/test/playground/lib/static-site-stack.ts
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/src/util/apiGatewayV2Domain.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
  www/docs/constructs/Api.md
  www/docs/constructs/ApiGatewayV1Api.md
Labels: bug

#468 sst start: .env variables not available when deploying debug stack
  packages/cli/assets/debug-stack/bin/index.js
  packages/cli/scripts/remove.js
  packages/cli/scripts/start.js
Labels: bug

#471 Adding a React.js example
  .eslintignore
  examples/.gitignore
  examples/.prettierignore
  examples/README.md
  examples/react-app/.gitignore
  examples/react-app/README.md
  examples/react-app/frontend/.env
  examples/react-app/frontend/.gitignore
  examples/react-app/frontend/README.md
  examples/react-app/frontend/package-lock.json
  examples/react-app/frontend/package.json
  examples/react-app/frontend/public/favicon.ico
  examples/react-app/frontend/public/index.html
  examples/react-app/frontend/public/logo192.png
  examples/react-app/frontend/public/logo512.png
  examples/react-app/frontend/public/manifest.json
  examples/react-app/frontend/public/robots.txt
  examples/react-app/frontend/src/App.css
  examples/react-app/frontend/src/App.js
  examples/react-app/frontend/src/App.test.js
  examples/react-app/frontend/src/index.css
  examples/react-app/frontend/src/index.js
  examples/react-app/frontend/src/logo.svg
  examples/react-app/frontend/src/reportWebVitals.js
  examples/react-app/frontend/src/setupTests.js
  examples/react-app/lib/MyStack.js
  examples/react-app/lib/index.js
  examples/react-app/package-lock.json
  examples/react-app/package.json
  examples/react-app/src/lambda.js
  examples/react-app/sst.json
  examples/react-app/test/MyStack.test.js
  www/docs/environment-variables.md
Labels: documentation

#475 StaticSite: support granular cacheControl and variable replacement
  packages/cli/test/playground/lib/static-site-stack.ts
  packages/cli/test/playground/src/sites/website/index.html
  packages/resources/assets/StaticSite/index.py
  packages/resources/src/StaticSite.ts
  packages/resources/test/StaticSite.test.ts
  www/docs/constructs/StaticSite.md
Labels: enhancement

#476 App: add account property
  packages/resources/src/App.ts
  packages/resources/src/Stack.ts
  www/docs/constructs/App.md
Labels: enhancement

#477 StaticSite: fix custom resource permission denied error
  packages/resources/assets/StaticSite/index.py
Labels: bug

#478 StaticSite: add error page option to auto-redirect to the index page
  packages/resources/src/StaticSite.ts
  packages/resources/test/StaticSite.test.ts
Labels: enhancement

#479 Updating docs with new error page option
  examples/react-app/lib/MyStack.js
  examples/react-app/package-lock.json
  examples/react-app/package.json
  www/docs/constructs/StaticSite.md
Labels: documentation

#480 StaticSite: do not build website on sst remove
  packages/cli/assets/cdk-wrapper/run.js
  packages/cli/test/helpers/index.js
  packages/cli/test/helpers/run-remove-command.js
  packages/cli/test/remove/lib/index.js
  packages/cli/test/remove/package.json
  packages/cli/test/remove/remove.test.js
  packages/cli/test/remove/src/lambda.js
  packages/cli/test/remove/sst.json
Labels: bug

#481 App: add account property
  packages/resources/src/App.ts
  packages/resources/test/Function.test.ts
  packages/resources/test/WebSocketApi.test.ts
Labels: enhancement

#491 StaticSite: skip building on sst start
  packages/cli/test/playground/lib/static-site-stack.ts
  packages/resources/assets/StaticSite/custom-resource/index.py
  packages/resources/assets/StaticSite/stub/index.html
  packages/resources/src/StaticSite.ts
  packages/resources/test/StaticSite.test.ts
Labels: enhancement

#494 Fix missing module lambda-layer-awscli
  packages/resources/package.json
Labels: bug

#495 Fixing spelling mistake in static site stub
  packages/resources/assets/StaticSite/stub/index.html
Labels: bug

#498 Function: add bundling command hooks
  packages/resources/src/Function.ts
  packages/resources/src/util/nodeBuilder.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/Function.md
Labels: enhancement

#497 Dynamically generating social cards for docs
  .eslintrc.json
  .prettierignore
  examples/.prettierignore
  examples/cron-job/src/lambda.js
  package.json
  packages/cli/lib/object.js
  packages/cli/scripts/util/CdkWatcherState.js
  packages/cli/scripts/util/LambdaRuntimeServer.js
  packages/cli/scripts/util/Watcher.js
  packages/cli/scripts/util/bootstrap.js
  packages/cli/test/base-python/lib/index.js
  packages/cli/test/bootstrap/bootstrap.test.js
  packages/cli/test/cdk-watcher-state/cdk-watcher-state.test.js
  packages/cli/test/dotenv/dotenv.test.js
  packages/cli/test/dotenv/lib/index.js
  packages/cli/test/go-build/go-build.test.js
  packages/cli/test/is-local/is-local.test.js
  packages/cli/test/lambda-override-tsconfig/lambda-override-tsconfig.test.js
  packages/cli/test/lambda-watcher-state/lambda-watcher-state.test.js
  packages/cli/test/lambda-watcher-state/lib/index.js
  packages/cli/test/lib/lib.test.js
  packages/cli/test/nodejs-build-bundle-no-srcpath/nodejs-build-bundle-no-srcpath.test.js
  packages/cli/test/nodejs-build-bundle-srcpath/nodejs-build-bundle-srcpath.test.js
  packages/cli/test/nodejs-build-no-bundle-srcpath/nodejs-build-no-bundle-srcpath.test.js
  packages/cli/test/playground/src/authorizer.js
  packages/cli/test/playground/src/lambdajs.js
  packages/cli/test/start-guide/lib/ApiStack.js
  packages/cli/test/start-guide/services/misc/handler.js
  packages/cli/test/start-handler-sync-async-cases/api.js
  packages/core/cancelablePromise.js
  packages/core/errorHelpers.js
  packages/resources/assets/stub/index.js
  www/docusaurus.config.js
  www/package.json
  www/src/theme/DocItem/index.js
  www/static/img/og-image.png
  www/yarn.lock
  yarn.lock
Labels: documentation
