Repository serverless-stack/sst, pull requests merged in 2021-03, with the labels that each got.

#164 Serverless Framework migration guide
  www/docs/migrating-from-cdk.md
  www/docs/migrating-from-serverless-framework.md
  www/sidebars.js
Labels: skip changelog

#165 Support payload format version in Api construct
  packages/resources/src/Api.ts
  packages/resources/test/Api.test.ts
  www/docs/constructs/Api.md
Labels: enhancement

#188 Support all CDK SNS topic options
  packages/cli/test/start-base/lib/index.js
  packages/cli/test/start-base/src/api/api.ts
  packages/cli/test/start-base/start-base.test.js
  packages/resources/src/Api.ts
  packages/resources/src/Topic.ts
  packages/resources/src/util/construct.ts
  packages/resources/src/util/permission.ts
  packages/resources/test/Topic.test.ts
  www/docs/constructs/Topic.md
Labels: enhancement

#190 Fix sst start crash for large lambda response
  packages/cli/assets/lambda-invoke/bootstrap.js
  packages/cli/scripts/start.js
Labels: bug

#196 Support all CDK DynamoDB table options
  packages/resources/src/Table.ts
  packages/resources/src/Topic.ts
  packages/resources/test/Table.test.ts
  www/docs/constructs/Table.md
Labels: enhancement

#197 Update design-principles.md
  www/docs/design-principles.md
Labels: documentation

#202 Support all CDK Http Api options
  packages/resources/src/Api.ts
  packages/resources/test/Api.test.ts
  www/docs/constructs/Api.md
  www/docs/constructs/Topic.md
Labels: enhancement

#203 Use the new stack as scope for adding new routes and subscribers
  packages/resources/src/Api.ts
  packages/resources/src/Topic.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/Topic.test.ts
Labels: bug

#212 Support all CDK SQS Queue options
  packages/resources/src/Api.ts
  packages/resources/src/Queue.ts
  packages/resources/src/Topic.ts
  packages/resources/test/Queue.test.ts
  www/docs/constructs/Queue.md
Labels: enhancement

#206 Fix handler code process.exit crashes sst start
  packages/cli/scripts/start.js
  packages/resources/lambda/stub/index.js
Labels: bug

#221 Handle Api.getFunction for non-existent route keys
  packages/resources/src/Api.ts
Labels: bug

#225 Support bundle options
  packages/cli/scripts/start.js
  packages/cli/test/build-bundle-copyfiles/build-bundle-copyfiles.test.js
  packages/cli/test/build-bundle-copyfiles/dirInRoot/fileInDir
  packages/cli/test/build-bundle-copyfiles/dirInRoot/sub/fileInDirSub
  packages/cli/test/build-bundle-copyfiles/fileInRoot
  packages/cli/test/build-bundle-copyfiles/lambda.js
  packages/cli/test/build-bundle-copyfiles/lib/index.js
  packages/cli/test/build-bundle-copyfiles/package.json
  packages/cli/test/build-bundle-copyfiles/src/fileInSrc
  packages/cli/test/build-bundle-copyfiles/src/lambda.js
  packages/cli/test/build-bundle-copyfiles/src/package.json
  packages/cli/test/build-bundle-copyfiles/sst.json
  packages/cli/test/build-bundle-externalmodules/build-bundle-externalmodules.test.js
  packages/cli/test/build-bundle-externalmodules/lambda.js
  packages/cli/test/build-bundle-externalmodules/lib/index.js
  packages/cli/test/build-bundle-externalmodules/package.json
  packages/cli/test/build-bundle-externalmodules/src/lambda.js
  packages/cli/test/build-bundle-externalmodules/src/package.json
  packages/cli/test/build-bundle-externalmodules/sst.json
  packages/cli/test/build-bundle-loader/build-bundle-loader.test.js
  packages/cli/test/build-bundle-loader/lambda.js
  packages/cli/test/build-bundle-loader/lib/index.js
  packages/cli/test/build-bundle-loader/package.json
  packages/cli/test/build-bundle-loader/sample.data
  packages/cli/test/build-bundle-loader/sst.json
  packages/cli/test/build-bundle-nodemodules/build-bundle-nodemodules.test.js
  packages/cli/test/build-bundle-nodemodules/lambda.js
  packages/cli/test/build-bundle-nodemodules/lib/index.js
  packages/cli/test/build-bundle-nodemodules/package.json
  packages/cli/test/build-bundle-nodemodules/src/lambda.js
  packages/cli/test/build-bundle-nodemodules/src/package.json
  packages/cli/test/build-bundle-nodemodules/sst.json
  packages/resources/src/Function.ts
  packages/resources/src/util/builder.ts
  www/docs/constructs/Function.md
  www/docs/migrating-from-serverless-framework.md
  yarn.lock
Labels: enhancement

#227 Fix typescript error when using imported constructs
  packages/resources/src/Api.ts
  packages/resources/src/Auth.ts
  packages/resources/src/Queue.ts
  packages/resources/src/Table.ts
  packages/resources/src/Topic.ts
Labels: bug

#229 Fix sync Lambda handler missing response value
  packages/cli/assets/lambda-invoke/bootstrap.js
Labels: bug

#233 Fix sync function handler returns RESPONSE null due to bad timing
  packages/cli/assets/lambda-invoke/bootstrap.js
  packages/cli/bin/scripts.js
Labels: bug

#237 Upgrading to latest TypeScript
  package.json
  packages/cli/package.json
  packages/resources/package.json
  yarn.lock
Labels: enhancement

#239 Add tests for Lambda bootstrapper
  packages/cli/assets/lambda-invoke/bootstrap.js
  packages/cli/test/bootstrap/bootstrap.test.js
  packages/cli/test/bootstrap/lambda.js
  packages/cli/test/bootstrap/package.json
  packages/cli/test/helpers/index.js
  packages/cli/test/helpers/run-bootstrap.js
Labels: skip changelog

#240 Add 'stage' property to Stack construct
  packages/resources/src/Stack.ts
Labels: enhancement

#246 Add IS_LOCAL environment variable when runing `sst start`
  packages/cli/scripts/start.js
Labels: enhancement

#249 Improves TS template method signature
  packages/create-serverless-stack/templates/typescript/src/lambda.ts
Labels: enhancement

#235 Adding examples to Function construct documentation
  www/docs/constructs/Function.md
Labels: documentation

#253 Adding doc on how to debug with VS Code
  www/docs/debugging-with-vscode.md
  www/sidebars.js
  www/static/img/screens/vs-code-lambda-function-breakpoint.png
  www/static/img/screens/vs-code-run-and-debug-tab.png
Labels: documentation

#258 Support DynamoDB streams in Table construct
  packages/resources/src/Table.ts
  packages/resources/src/Topic.ts
  packages/resources/test/Table.test.ts
  www/docs/constructs/Table.md
  www/docs/migrating-from-serverless-framework.md
Labels: enhancement

#259 Support attaching Function invoke permissions
  packages/resources/src/util/permission.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/Function.md
Labels: enhancement

#261 Add Bucket construct
  packages/resources/src/Bucket.ts
  packages/resources/src/index.ts
  packages/resources/src/util/permission.ts
  packages/resources/test/Bucket.test.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/Bucket.md
  www/sidebars.js
Labels: enhancement

#262 Add syntactic sugar for adding Stack outputs
  packages/resources/src/Stack.ts
  packages/resources/test/Stack.test.ts
  www/docs/constructs/Stack.md
Labels: enhancement

#265 Support outputs file option for sst start
  packages/cli/bin/scripts.js
  packages/cli/scripts/deploy.js
  packages/cli/scripts/start.js
  www/docs/packages/cli.md
Labels: enhancement

#266 Add typeCheck option in sst.json to configure type checking
  packages/cli/assets/cdk-wrapper/run.js
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/eslint-disabled-ts/tsconfig.json
  packages/cli/test/typecheck-disabled-ts/lambda.ts
  packages/cli/test/typecheck-disabled-ts/lib/index.d.ts
  packages/cli/test/typecheck-disabled-ts/lib/index.js
  packages/cli/test/typecheck-disabled-ts/lib/index.ts
  packages/cli/test/typecheck-disabled-ts/package.json
  packages/cli/test/typecheck-disabled-ts/sst.json
  packages/cli/test/typecheck-disabled-ts/tsconfig.json
  packages/cli/test/typecheck-disabled-ts/typecheck-disabled-ts.test.js
  packages/create-serverless-stack/templates/typescript/sst.template.json
  packages/resources/src/App.ts
  www/docs/installation.md
Labels: enhancement

#267 Add ApolloApi construct
  packages/resources/src/Api.ts
  packages/resources/src/ApolloApi.ts
  packages/resources/src/index.ts
  packages/resources/test/ApolloApi.test.ts
  www/docs/constructs/ApolloApi.md
  www/sidebars.js
Labels: enhancement

#272 Fix missing stack events on sst deploy
  packages/core/index.js
Labels: bug

#273 Fix `sst cdk` not invoking cdk commands
  packages/cli/scripts/cdk.js
  packages/cli/scripts/util/cdkHelpers.js
Labels: bug

#275 Configure esbuild logLevel based on the `verbose` flag
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/resources/src/util/builder.ts
Labels: enhancement

#277 Implement AppSyncApi construct
  packages/resources/package.json
  packages/resources/src/AppSyncApi.ts
  packages/resources/src/Function.ts
  packages/resources/src/index.ts
  packages/resources/src/util/permission.ts
  packages/resources/test/AppSyncApi.test.ts
  packages/resources/test/Function.test.ts
  packages/resources/test/schema.graphql
  www/docs/constructs/AppSyncApi.md
  www/sidebars.js
  yarn.lock
Labels: enhancement

#281 Add domain and certificate props for Api construct
  packages/resources/src/Api.ts
  packages/resources/test/Api.test.ts
Labels: enhancement
