Repository serverless-stack/sst, pull requests merged in 2021-05, with the labels that each got.

#361 Auth: add support for UserPool triggers
  packages/resources/src/Auth.ts
  packages/resources/test/Auth.test.ts
  www/docs/constructs/Auth.md
Labels: enhancement

#364 Add helper message to run `sst deploy` after stopping `sst start`
  packages/cli/scripts/start.js
  packages/cli/scripts/util/LambdaRuntimeServer.js
  packages/cli/scripts/util/Watcher.js
Labels: enhancement

#365 Editing auth triggers docs changes
  README.md
  www/docs/constructs/Auth.md
  www/docs/migrating-from-serverless-framework.md
  www/docs/packages/resources.md
Labels: documentation

#366 Editing docs with SST auto-rebuilding CDK code
  www/docs/packages/cli.md
Labels: documentation

#368 sst start: fix new handlers added through live infrastructure reload are not watched
  packages/cli/bin/scripts.js
  packages/cli/lib/array.js
  packages/cli/scripts/start.js
  packages/cli/scripts/util/CdkWatcherState.js
  packages/cli/scripts/util/LambdaWatcherState.js
  packages/cli/scripts/util/Watcher.js
  packages/cli/test/cdk-watcher-state/cdk-watcher-state.test.js
  packages/cli/test/cdk-watcher-state/package.json
  packages/cli/test/lambda-watcher-state/lambda-watcher-state.test.js
  packages/cli/test/lambda-watcher-state/lib/index.js
  packages/cli/test/lambda-watcher-state/package.json
  packages/cli/test/watcher-cdk-state/watcher-cdk-state.test.js
  packages/cli/test/watcher/go.mod
  packages/cli/test/watcher/go.sum
  packages/cli/test/watcher/lambda.go
  packages/cli/test/watcher/lambda.js
  packages/cli/test/watcher/watcher.test.js
Labels: bug

#369 sst start: Fix AWS_PROFILE used over AWS_ACCESS_KEY_ID when aws sdk v3 is used inside Lambda functions
  packages/cli/scripts/start.js
Labels: bug

#371 sst start: Fix websocket connection exits with WebSocket is not open error
  packages/cli/scripts/start.js
Labels: bug

#372 sst start: Retry deploying infrastructure changes after a failed deploy
  packages/cli/scripts/util/CdkWatcherState.js
  packages/cli/test/cdk-watcher-state/cdk-watcher-state.test.js
Labels: enhancement

#373 Function: Fix no code change results in different lambda zip hash
  packages/cli/test/nodejs-build-bundle-no-srcpath/lib/index.js
  packages/cli/test/nodejs-build-bundle-no-srcpath/nodejs-build-bundle-no-srcpath.test.js
  packages/cli/test/nodejs-build-bundle-no-srcpath/service/lambda.js
  packages/cli/test/nodejs-build-bundle-no-srcpath/service/src/lambda.js
  packages/cli/test/nodejs-build-bundle-no-srcpath/src/srcLambda.js
  packages/cli/test/nodejs-build-bundle-srcpath/lambda.js
  packages/cli/test/nodejs-build-bundle-srcpath/lib/index.js
  packages/cli/test/nodejs-build-bundle-srcpath/nodejs-build-bundle-srcpath.test.js
  packages/cli/test/nodejs-build-bundle-srcpath/service/src/lambda.js
  packages/cli/test/nodejs-build-bundle-srcpath/service/src/srcLambda.js
  packages/cli/test/nodejs-build-bundle-srcpath/src/lambda.js
  packages/resources/src/Function.ts
  packages/resources/src/util/goBuilder.ts
  packages/resources/src/util/nodeBuilder.ts
  packages/resources/src/util/pythonBuilder.ts
Labels: bug

#378 Api: Support Lambda authorizer
  packages/cli/package.json
  packages/cli/test/base-go/package.json
  packages/cli/test/base-python/package.json
  packages/cli/test/base-ts/package.json
  packages/cli/test/base/package.json
  packages/cli/test/bootstrap/package.json
  packages/cli/test/config/package.json
  packages/cli/test/context/package.json
  packages/cli/test/dotenv/package.json
  packages/cli/test/eslint-lambda-override-eslintrc/package.json
  packages/cli/test/go-build/package.json
  packages/cli/test/is-local/package.json
  packages/cli/test/jest-ts/package.json
  packages/cli/test/jest/package.json
  packages/cli/test/lambda-override-tsconfig/package.json
  packages/cli/test/lambda-watcher-state/package.json
  packages/cli/test/nodejs-build-bundle-copyfiles/package.json
  packages/cli/test/nodejs-build-bundle-externalmodules/package.json
  packages/cli/test/nodejs-build-bundle-loader/package.json
  packages/cli/test/nodejs-build-bundle-no-srcpath/package.json
  packages/cli/test/nodejs-build-bundle-nodemodules/package.json
  packages/cli/test/nodejs-build-bundle-srcpath/package.json
  packages/cli/test/nodejs-build-no-bundle-no-srcpath/package.json
  packages/cli/test/nodejs-build-no-bundle-srcpath/package.json
  packages/cli/test/playground/lib/api-with-lambda-authorizer.ts
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/package.json
  packages/cli/test/rest-api-auth-cognito/package.json
  packages/cli/test/stack-no-prefix/package.json
  packages/cli/test/start-base/package.json
  packages/cli/test/start-demo/package.json
  packages/cli/test/start-guide/package.json
  packages/cli/test/start-handler-sync-async-cases/package.json
  packages/cli/test/start-no-src-path/package.json
  packages/cli/test/template-app-ts/package.json
  packages/cli/test/template-app/package.json
  packages/core/package.json
  packages/resources/package.json
  packages/resources/src/Api.ts
  packages/resources/src/App.ts
  packages/resources/src/Auth.ts
  packages/resources/src/Function.ts
  packages/resources/src/util/apiGatewayV2Domain.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/Auth.test.ts
  www/docs/constructs/Api.md
  yarn.lock
Labels: enhancement

#384 KinesisStream: Add construct for Kinesis streams
  README.md
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/lib/kinesis-stream.ts
  packages/resources/package.json
  packages/resources/src/KinesisStream.ts
  packages/resources/src/Topic.ts
  packages/resources/src/index.ts
  packages/resources/src/util/permission.ts
  packages/resources/test/KinesisStream.test.ts
  www/docs/constructs/Bucket.md
  www/docs/constructs/Function.md
  www/docs/constructs/KinesisStream.md
  www/sidebars.js
Labels: enhancement

#389 sst start: pass system env vars to spawned lambda process
  packages/cli/scripts/start.js
  packages/cli/test/playground/.vscode/launch.json
Labels: bug

#392 sst start: fix Lambda watcher not able to run for non-NodeJS functions
  packages/cli/scripts/util/LambdaWatcherState.js
Labels: bug

#393 sst start: fix rebuilding code message not shown when lint and typeCheck are disabled
  packages/cli/scripts/start.js
Labels: bug

#390 Topic: support Queue subscribers
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/lib/topic-to-queue-stack.ts
  packages/cli/test/playground/src/lambda.ts
  packages/resources/src/Topic.ts
  packages/resources/test/Topic.test.ts
  www/docs/constructs/Topic.md
Labels: enhancement

#394 Fixes to the docs
  www/docs/constructs/Api.md
  www/docs/constructs/KinesisStream.md
  www/docs/constructs/Table.md
  www/docs/constructs/Topic.md
  www/docs/live-lambda-development.md
  www/docs/packages/resources.md
  www/docs/working-locally.md
Labels: documentation

#398 sst deploy/remove: use exit code 1 if stacks failed to deploy or remove
  packages/cli/scripts/deploy.js
  packages/cli/scripts/remove.js
  packages/core/index.js
Labels: bug

#401 sst start: disable Function retry
  packages/cli/test/playground/lib/cron-stack.ts
  packages/cli/test/playground/lib/index.ts
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
Labels: enhancement

#402 sst start: extend timeout to 900s
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
Labels: enhancement
