Repository serverless-stack/sst, pull requests merged in 2021-11, with the labels that each got.

#979 sst start: set log retention in debug stack - #883
  packages/cli/assets/debug-stack/lib/DebugStack.js
Labels: enhancement

#994 Tweaking copy for static site placeholder site
  packages/resources/assets/StaticSite/stub/index.html
Labels: documentation

#995 Fixing steps for Epsagon in docs
  www/docs/monitoring-your-app-in-prod.md
Labels: documentation

#1005 Doc: add Thundra integration
  www/docs/monitoring-your-app-in-prod.md
Labels: documentation

#982 Fix for breakpoints causing disconnects
  packages/cli/package.json
  yarn.lock
Labels: bug

#1015 Function: use placeholder Code asset instance instead of inline on sst remove
  packages/resources/assets/Function/placeholder-stub/lambda.js
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
Labels: enhancement

#1002 Add type definitions for Node and ensure that the major version is the same with default runtime
  packages/create-serverless-stack/templates/typescript/package.template.json
Labels: bug

#1018 Fix extra certs issue
  packages/resources/assets/stub/index.js
Labels: bug

#1025 Prototype for UDP based communication with AWS
  .github/workflows/ci.yml
  examples/prisma/yarn.lock
  packages/cli/assets/cdk-wrapper/run.js
  packages/cli/assets/debug-stack/lambda/wsDefault.js
  packages/cli/bin/scripts.js
  packages/cli/scripts/start.js
  packages/core/package.json
  packages/core/src/bridge/bridge.ts
  packages/core/src/bridge/index.ts
  packages/core/src/index.js
  packages/core/src/types.d.ts
  packages/resources/assets/bridge_client/bridge_client.go
  packages/resources/assets/bridge_client/go.mod
  packages/resources/assets/bridge_client/go.sum
  packages/resources/bin/build-bridge-client.js
  packages/resources/package.json
  packages/resources/src/App.ts
  packages/resources/src/Function.ts
  packages/resources/src/util/goBuilder.ts
  yarn.lock
Labels: enhancement

#992 Allow customize access log retention (Api, WebSocketApi, ApiGatewayV1Api)
  packages/resources/src/Api.ts
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/src/WebSocketApi.ts
  packages/resources/src/util/apiGatewayV1AccessLog.ts
  packages/resources/src/util/apiGatewayV2AccessLog.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
  packages/resources/test/WebSocketApi.test.ts
  www/docs/constructs/Api.md
  www/docs/constructs/ApiGatewayV1Api.md
  www/docs/constructs/WebSocketApi.md
Labels: enhancement

#1027 All fixes in place
  packages/cli/scripts/start.js
  packages/core/src/bridge/bridge.ts
  packages/resources/assets/bridge_client/bridge_client.go
  packages/resources/assets/bridge_client/go.mod
  packages/resources/assets/bridge_client/go.sum
Labels: bug

#1028 Implement packet splitting for udp responses
  packages/cli/scripts/start.js
  packages/core/src/bridge/bridge.ts
  packages/resources/assets/bridge_client/bridge_client.go
  packages/resources/assets/bridge_client/go.mod
  packages/resources/assets/bridge_client/go.sum
Labels: bug

#989 added Datadog example
  examples/README.md
  examples/datadog/.gitignore
  examples/datadog/README.md
  examples/datadog/package.json
  examples/datadog/src/lambda.js
  examples/datadog/sst.json
  examples/datadog/stacks/MyStack.js
  examples/datadog/stacks/index.js
  examples/datadog/test/MyStack.test.js
Labels: documentation

#997 Added Sentry example
  examples/README.md
  examples/sentry/.gitignore
  examples/sentry/README.md
  examples/sentry/package.json
  examples/sentry/src/lambda.js
  examples/sentry/sst.json
  examples/sentry/stacks/MyStack.js
  examples/sentry/stacks/index.js
  examples/sentry/test/MyStack.test.js
Labels: documentation

#1050 Update CDK to v1.132.0
  packages/cli/package.json
  packages/cli/test/base-dotnet/package.json
  packages/cli/test/base-go/package.json
  packages/cli/test/base-python/package.json
  packages/cli/test/base-ts/package.json
  packages/cli/test/base-tsx/package.json
  packages/cli/test/base/package.json
  packages/cli/test/config-main-js/package.json
  packages/cli/test/config-main-ts/package.json
  packages/cli/test/config/package.json
  packages/cli/test/context/package.json
  packages/cli/test/dotenv/package.json
  packages/cli/test/dotnet-build/package.json
  packages/cli/test/eslint-lambda-override-eslintrc/package.json
  packages/cli/test/go-build/package.json
  packages/cli/test/is-local/package.json
  packages/cli/test/jest-ts/package.json
  packages/cli/test/jest/package.json
  packages/cli/test/lambda-override-tsconfig/package.json
  packages/cli/test/lambda-watcher-state/package.json
  packages/cli/test/nodejs-build-bundle-copyfiles/package.json
  packages/cli/test/nodejs-build-bundle-esbuildconfig/package.json
  packages/cli/test/nodejs-build-bundle-externalmodules/package.json
  packages/cli/test/nodejs-build-bundle-loader/package.json
  packages/cli/test/nodejs-build-bundle-no-srcpath/package.json
  packages/cli/test/nodejs-build-bundle-nodemodules/package.json
  packages/cli/test/nodejs-build-bundle-srcpath/package.json
  packages/cli/test/nodejs-build-no-bundle-no-srcpath/package.json
  packages/cli/test/nodejs-build-no-bundle-srcpath/package.json
  packages/cli/test/nodejs-handler-filename-with-dot/package.json
  packages/cli/test/nodejs-handler-relative-path/package.json
  packages/cli/test/playground/package.json
  packages/cli/test/remove/package.json
  packages/cli/test/rest-api-auth-cognito/package.json
  packages/cli/test/stack-no-prefix/package.json
  packages/cli/test/start-base/package.json
  packages/cli/test/start-demo/package.json
  packages/cli/test/start-guide/package.json
  packages/cli/test/start-handler-sync-async-cases/package.json
  packages/cli/test/start-no-src-path/package.json
  packages/cli/test/template-app-ts/package.json
  packages/cli/test/template-app/package.json
  packages/cli/test/update/package.json
  packages/core/package.json
  packages/resources/package.json
  packages/resources/test/Api.test.ts
  www/docs/constructs/Api.md
  yarn.lock
Labels: enhancement

#1051 EventBus: fix event bus cannot be imported by name
  packages/cli/test/playground/lib/eventbus-stack.ts
  packages/cli/test/playground/lib/index.ts
  packages/resources/src/EventBus.ts
  packages/resources/test/EventBus.test.ts
Labels: bug

#1052 Console: incorrect route path in Api panel for custom stage
  packages/cli/scripts/util/ConstructsState.js
  packages/cli/test/playground/lib/api-stack.ts
  packages/cli/test/playground/package.json
Labels: bug

#1053 Table: add instructions for importing tables with stream enabled
  packages/resources/src/Table.ts
  packages/resources/test/Table.test.ts
Labels: documentation

#1054 Core: after a deploy failure, redeploy detects no changes
  packages/core/src/index.js
Labels: bug

#1074 Fix building bridge on windows
  packages/resources/package.json
Labels: bug

#1029 cli: hide CDK and StaticSite outputs from stack outputs
  packages/cli/scripts/deploy.js
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/cdkHelpers/cdkHelpers.test.js
  packages/cli/test/cdkHelpers/package.json
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/output.json
  www/docs/packages/cli.md
Labels: enhancement

#1019 Added middy validation example
  examples/README.md
  examples/middy-validator/.env
  examples/middy-validator/.gitignore
  examples/middy-validator/README.md
  examples/middy-validator/package.json
  examples/middy-validator/src/lambda.js
  examples/middy-validator/sst.json
  examples/middy-validator/stacks/MyStack.js
  examples/middy-validator/stacks/index.js
  examples/middy-validator/test/MyStack.test.js
Labels: documentation

#1083 Fix for crashed processes
  packages/core/src/runtime/server.ts
Labels: bug

#1040 Added example for debugging in Intellij IDEA
  examples/README.md
  examples/intellij-idea/.env
  examples/intellij-idea/.gitignore
  examples/intellij-idea/.idea/.gitignore
  examples/intellij-idea/.idea/inspectionProfiles/Project_Default.xml
  examples/intellij-idea/.idea/intellij-idea.iml
  examples/intellij-idea/.idea/modules.xml
  examples/intellij-idea/.idea/runConfigurations.xml
  examples/intellij-idea/.idea/vcs.xml
  examples/intellij-idea/README.md
  examples/intellij-idea/package.json
  examples/intellij-idea/src/lambda.js
  examples/intellij-idea/sst.json
  examples/intellij-idea/stacks/MyStack.js
  examples/intellij-idea/stacks/index.js
  examples/intellij-idea/test/MyStack.test.js
Labels: documentation

#1087 EventBus: cannot import using bus ARN where the ARN is a CDK import
  packages/cli/assets/cdk-wrapper/run.js
  packages/cli/assets/console/src/components/ApiConstructPanel.js
  packages/cli/assets/console/src/components/ConstructPanel.js
  packages/cli/assets/console/src/components/CronConstructPanel.js
  packages/cli/assets/console/src/components/KinesisStreamConstructPanel.js
  packages/cli/assets/console/src/components/QueueConstructPanel.js
  packages/cli/assets/console/src/components/TopicConstructPanel.js
  packages/cli/assets/console/src/components/WebSocketApiConstructPanel.js
  packages/cli/assets/console/src/stories/ApiConstructPanel.stories.jsx
  packages/cli/assets/console/src/stories/ConstructsPanel.stories.jsx
  packages/cli/assets/console/src/stories/CronConstructPanel.stories.jsx
  packages/cli/assets/console/src/stories/KinesisStreamConstructPanel.stories.jsx
  packages/cli/assets/console/src/stories/QueueConstructPanel.stories.jsx
  packages/cli/assets/console/src/stories/TopicConstructPanel.stories.jsx
  packages/cli/assets/console/src/stories/WebSocketApiConstructPanel.stories.jsx
  packages/cli/scripts/start.js
  packages/cli/scripts/util/ConstructsState.js
  packages/cli/test/playground/lib/empty-stack.ts
  packages/cli/test/playground/lib/eventbus-stack.ts
  packages/cli/test/playground/lib/index.ts
  packages/resources/assets/NextjsSite/edge-lambda-stub/index.js
  packages/resources/src/Api.ts
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/src/App.ts
  packages/resources/src/AppSyncApi.ts
  packages/resources/src/Auth.ts
  packages/resources/src/Bucket.ts
  packages/resources/src/Construct.ts
  packages/resources/src/Cron.ts
  packages/resources/src/EventBus.ts
  packages/resources/src/KinesisStream.ts
  packages/resources/src/NextjsSite.ts
  packages/resources/src/Queue.ts
  packages/resources/src/Stack.ts
  packages/resources/src/StaticSite.ts
  packages/resources/src/Table.ts
  packages/resources/src/Topic.ts
  packages/resources/src/WebSocketApi.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
  packages/resources/test/App.test.ts
  packages/resources/test/AppSyncApi.test.ts
  packages/resources/test/Auth.test.ts
  packages/resources/test/Bucket.test.ts
  packages/resources/test/Cron.test.ts
  packages/resources/test/EventBus.test.ts
  packages/resources/test/KinesisStream.test.ts
  packages/resources/test/Queue.test.ts
  packages/resources/test/Table.test.ts
  packages/resources/test/Topic.test.ts
  packages/resources/test/WebSocketApi.test.ts
Labels: bug

#1096 Fix sst deploy fail with error "Cannot convert undefined or null to object
  packages/cli/scripts/util/cdkHelpers.js
  packages/core/src/index.js
Labels: bug

#1098 sst deploy: UPDATE_FAILED shown instead of the actual error message
  packages/core/src/index.js
Labels: bug
