Repository serverless-stack/sst, pull requests merged in 2021-07, with the labels that each got.

#510 AppSyncApi: do not normalize resolver key cases
  packages/resources/src/AppSyncApi.ts
  packages/resources/test/AppSyncApi.test.ts
Labels: bug

#511 Cron: allow configuring event payload
  packages/cli/test/playground/lib/cron-stack.ts
  packages/resources/src/Cron.ts
  packages/resources/test/Cron.test.ts
  www/docs/constructs/Cron.md
Labels: enhancement

#515 Function: support custom install commands for Python runtime
  packages/resources/assets/python/Dockerfile.custom
  packages/resources/src/Function.ts
  packages/resources/src/util/nodeBuilder.ts
  packages/resources/src/util/python/bundling.ts
  packages/resources/src/util/pythonBuilder.ts
  www/docs/constructs/Function.md
Labels: enhancement

#516 Api: check for duplicated routes at build time
  packages/resources/src/Api.ts
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/src/WebSocketApi.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
  packages/resources/test/WebSocketApi.test.ts
Labels: enhancement

#517 Improving docs for bundling props
  www/docs/constructs/Api.md
  www/docs/constructs/Function.md
Labels: documentation

#520 Api: add routes property
  packages/resources/src/Api.ts
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/src/WebSocketApi.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
  packages/resources/test/WebSocketApi.test.ts
  www/docs/constructs/Api.md
  www/docs/constructs/ApiGatewayV1Api.md
  www/docs/constructs/WebSocketApi.md
Labels: enhancement

#521 Update CDK to 1.111.0
  packages/cli/package.json
  packages/cli/test/base-go/package.json
  packages/cli/test/base-python/package.json
  packages/cli/test/base-ts/package.json
  packages/cli/test/base/package.json
  packages/cli/test/bootstrap/package.json
  packages/cli/test/config/package.json
  packages/cli/test/context/package.json
  packages/cli/test/dotenv/package.json
  packages/cli/test/eslint-lambda-override-eslintrc/package.json
  packages/cli/test/go-build/package.json
  packages/cli/test/is-local/package.json
  packages/cli/test/jest-ts/package.json
  packages/cli/test/jest/package.json
  packages/cli/test/lambda-override-tsconfig/package.json
  packages/cli/test/lambda-watcher-state/package.json
  packages/cli/test/nodejs-build-bundle-copyfiles/package.json
  packages/cli/test/nodejs-build-bundle-externalmodules/package.json
  packages/cli/test/nodejs-build-bundle-loader/package.json
  packages/cli/test/nodejs-build-bundle-no-srcpath/package.json
  packages/cli/test/nodejs-build-bundle-nodemodules/package.json
  packages/cli/test/nodejs-build-bundle-srcpath/package.json
  packages/cli/test/nodejs-build-no-bundle-no-srcpath/package.json
  packages/cli/test/nodejs-build-no-bundle-srcpath/package.json
  packages/cli/test/playground/package.json
  packages/cli/test/remove/package.json
  packages/cli/test/rest-api-auth-cognito/package.json
  packages/cli/test/stack-no-prefix/package.json
  packages/cli/test/start-base/package.json
  packages/cli/test/start-demo/package.json
  packages/cli/test/start-guide/package.json
  packages/cli/test/start-handler-sync-async-cases/package.json
  packages/cli/test/start-no-src-path/package.json
  packages/cli/test/template-app-ts/package.json
  packages/cli/test/template-app/package.json
  packages/core/package.json
  packages/resources/package.json
  yarn.lock
Labels: enhancement

#524 docs(deploying-your-app) Fix small typo
  www/docs/deploying-your-app.md
Labels: documentation

#536 sst start: importing files fails with ModuleNotFoundError for Python runtimes
  packages/cli/scripts/start.js
  packages/cli/scripts/util/bootstrap.py
Labels: bug

#533 create-serverless-stack: default runtime not set for fix tests in the non-Node.js templates
  packages/create-serverless-stack/templates/go/test/%stack-name.PascalCased%.test.template.js
  packages/create-serverless-stack/templates/python/test/%stack-name.PascalCased%.test.template.js
Labels: bug

#525 ReactStaticSite: with React environment variable integration
  README.md
  package.json
  packages/cli/assets/cdk-wrapper/run.js
  packages/cli/lib/array.js
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/playground/lib/api-stack.ts
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/lib/react-static-site-stack.ts
  packages/cli/test/playground/src/sites/react-app/package.json
  packages/cli/test/playground/src/sites/react-app/public/index.html
  packages/cli/test/playground/src/sites/react-app/src/App.js
  packages/cli/test/playground/src/sites/react-app/yarn.lock
  packages/resources/assets/StaticSite/custom-resource/index.py
  packages/resources/src/App.ts
  packages/resources/src/ReactStaticSite.ts
  packages/resources/src/StaticSite.ts
  packages/resources/src/index.ts
  packages/resources/test/ReactStaticSite.test.ts
  packages/resources/test/site/build/index.html
  packages/resources/test/site/package.json
  packages/static-site-env/bin/scripts.js
  packages/static-site-env/package.json
  packages/static-site-env/test/base/.build/static-site-environment-output-values.json
  packages/static-site-env/test/base/base.test.js
  packages/static-site-env/test/base/package.json
  packages/static-site-env/test/base/sst.json
  packages/static-site-env/test/helpers/index.js
  packages/static-site-env/test/helpers/run-start-command.js
  packages/static-site-env/test/sst-app-not-exist/package.json
  packages/static-site-env/test/sst-app-not-exist/sst-app-not-exist.test.js
  packages/static-site-env/test/sst-env-outputs-file-not-exist/package.json
  packages/static-site-env/test/sst-env-outputs-file-not-exist/sst-env-outputs-file-not-exist.test.js
  packages/static-site-env/test/sst-env-outputs-file-not-exist/sst.json
  packages/static-site-env/test/sst-env-outputs-not-found/.build/static-site-environment-output-values.json
  packages/static-site-env/test/sst-env-outputs-not-found/package.json
  packages/static-site-env/test/sst-env-outputs-not-found/sst-env-outputs-not-found.test.js
  packages/static-site-env/test/sst-env-outputs-not-found/sst.json
  www/docs/constructs/ReactStaticSite.md
  www/sidebars.js
Labels: enhancement

#554 Adding docs for ReactStaticSite and sst-env
  packages/cli/README.md
  packages/core/README.md
  packages/create-serverless-stack/README.md
  packages/resources/README.md
  packages/static-site-env/README.md
  packages/static-site-env/package.json
  www/docs/constructs/ReactStaticSite.md
  www/docs/packages/cli.md
  www/docs/packages/create-serverless-stack.md
  www/docs/packages/resources.md
  www/docs/packages/static-site-env.md
  www/sidebars.js
Labels: documentation

#552 Function: support granting permissions to RDS ServerlessCluster
  packages/resources/src/util/permission.ts
  www/docs/constructs/Function.md
Labels: enhancement

#557 Updating react example
  examples/react-app/frontend/package-lock.json
  examples/react-app/frontend/package.json
  examples/react-app/frontend/src/App.js
  examples/react-app/lib/MyStack.js
  examples/react-app/package-lock.json
  examples/react-app/package.json
Labels: documentation

#558 Updating README for packages
  packages/create-serverless-stack/README.md
  packages/resources/README.md
  packages/static-site-env/README.md
  www/docs/packages/resources.md
  www/docs/packages/static-site-env.md
Labels: documentation

#561 Updating docs for esbuild config
  packages/resources/assets/nodejs/esbuild.js
  www/docs/constructs/Function.md
  www/docs/packages/create-serverless-stack.md
Labels: documentation

#563 StaticSite: support sites larger than 500MB
  packages/resources/assets/StaticSite/archiver.js
  packages/resources/assets/StaticSite/custom-resource/index.py
  packages/resources/assets/StaticSite/custom-resource/s3-upload.py
  packages/resources/src/StaticSite.ts
  packages/resources/test/ReactStaticSite.test.ts
  packages/resources/test/StaticSite.test.ts
  packages/resources/test/site/build-with-30b-data/24byte.html
  packages/resources/test/site/build-with-30b-data/6byte.html
Labels: enhancement

#566 Bucket: support Queue and Topic notifications
  packages/resources/package.json
  packages/resources/src/Bucket.ts
  packages/resources/test/Bucket.test.ts
  www/docs/constructs/Bucket.md
Labels: enhancement

#571 Stack: improve error messaging for invalid stack props
  packages/cli/test/stack-set-env/stack-set-env.test.js
  packages/resources/src/Stack.ts
  packages/resources/src/util/construct.ts
  packages/resources/test/Stack.test.ts
Labels: enhancement

#573 Migration guide: add an example of hybrid multi-service Serverless Framework and SST app
  www/docs/migrating-from-serverless-framework.md
Labels: documentation

#574 Doc: explain the design choice behind using esbuild
  www/docs/faq.md
Labels: documentation

#576 Api: support ALB routes
  packages/resources/package.json
  packages/resources/src/Api.ts
  packages/resources/src/ApolloApi.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApolloApi.test.ts
  www/docs/constructs/Api.md
  www/docs/constructs/ApolloApi.md
Labels: enhancement

#578 ReactStaticSite: display React environment variables after deploying
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/playground/lib/react-static-site-stack.ts
  packages/resources/src/ReactStaticSite.ts
Labels: enhancement

#575 Support esbuild config in sst config
  packages/cli/assets/cdk-wrapper/run.js
  packages/cli/bin/scripts.js
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/config-esbuildconfig-invalid/config-esbuildconfig-invalid.test.js
  packages/cli/test/config-esbuildconfig-invalid/esbuild-config.js
  packages/cli/test/config-esbuildconfig-invalid/lib/index.js
  packages/cli/test/config-esbuildconfig-invalid/package.json
  packages/cli/test/config-esbuildconfig-invalid/sst.json
  packages/cli/test/config-esbuildconfig-non-plugins/config-esbuildconfig-non-plugins.test.js
  packages/cli/test/config-esbuildconfig-non-plugins/esbuild-config.js
  packages/cli/test/config-esbuildconfig-non-plugins/lib/index.js
  packages/cli/test/config-esbuildconfig-non-plugins/package.json
  packages/cli/test/config-esbuildconfig-non-plugins/sst.json
  packages/cli/test/config-esbuildconfig-not-found/config-esbuildconfig-not-found.test.js
  packages/cli/test/config-esbuildconfig-not-found/lib/index.js
  packages/cli/test/config-esbuildconfig-not-found/package.json
  packages/cli/test/config-esbuildconfig-not-found/sst.json
  packages/cli/test/config-esbuildconfig-not-set/config-esbuildconfig-not-set.test.js
  packages/cli/test/config-esbuildconfig-not-set/esbuild-config.js
  packages/cli/test/config-esbuildconfig-not-set/lib/index.ts
  packages/cli/test/config-esbuildconfig-not-set/package.json
  packages/cli/test/config-esbuildconfig-not-set/sst.json
  packages/cli/test/config-esbuildconfig-not-set/tsconfig.json
  packages/cli/test/config-esbuildconfig/config-esbuildconfig.test.js
  packages/cli/test/config-esbuildconfig/esbuild-config.js
  packages/cli/test/config-esbuildconfig/lib/index.ts
  packages/cli/test/config-esbuildconfig/package.json
  packages/cli/test/config-esbuildconfig/sst.json
  packages/cli/test/config-esbuildconfig/tsconfig.json
  packages/resources/src/App.ts
  packages/resources/src/Function.ts
  packages/resources/src/util/nodeBuilder.ts
  packages/resources/test/Function.test.ts
  www/docs/installation.md
Labels: enhancement

#587 Template: add .env to starter template
  packages/create-serverless-stack/templates/go/.env
  packages/create-serverless-stack/templates/go/.template.gitignore
  packages/create-serverless-stack/templates/javascript/.env
  packages/create-serverless-stack/templates/javascript/.template.gitignore
  packages/create-serverless-stack/templates/python/.env
  packages/create-serverless-stack/templates/python/.template.gitignore
  packages/create-serverless-stack/templates/typescript/.env
  packages/create-serverless-stack/templates/typescript/.template.gitignore
Labels: enhancement

#586 Template: add python compiled files to .gitignore
  packages/create-serverless-stack/templates/python/.template.gitignore
Labels: enhancement

#590 Function: support sharing layers across stacks
  packages/resources/package.json
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/Function.md
Labels: enhancement

#591 ApolloApi: fix CORS not working if authorization is enabled
  packages/resources/src/ApolloApi.ts
  packages/resources/test/ApolloApi.test.ts
Labels: bug

#594 sst test: support .env environment variables for running tests
  packages/cli/scripts/test.js
  www/docs/environment-variables.md
Labels: enhancement

#595 sst start: send descriptive error response when disconnected
  packages/resources/assets/stub/index.js
  packages/resources/src/Api.ts
  packages/resources/src/ApiGatewayV1Api.ts
Labels: enhancement

#599 Doc: add TypeScript examples for cross stack references
  packages/cli/test/playground/lib/api-stack.ts
  packages/cli/test/playground/lib/react-static-site-stack.ts
  www/docs/constructs/Api.md
  www/docs/constructs/Auth.md
Labels: documentation

#602 Editing docs for `sst.json` config
  www/docs/constructs/Function.md
  www/docs/environment-variables.md
  www/docs/installation.md
Labels: documentation

#609 StaticSite: allow extending the function for creating Route 53 records
  packages/resources/src/StaticSite.ts
  packages/resources/test/StaticSite.test.ts
Labels: enhancement

#610 sst start: force include aws-sdk as esbuild externals
  packages/cli/scripts/start.js
Labels: enhancement

#612 ReactStaticSite: display environment variables in sst deploy output
  packages/cli/assets/cdk-wrapper/run.js
  packages/resources/src/App.ts
Labels: bug

#611 sst start: crash if functions has multiple dot in the handler
  packages/cli/scripts/start.js
  packages/cli/test/nodejs-handler-filename-with-dot/lambda-handler-filename-with-dot.test.js
  packages/cli/test/nodejs-handler-filename-with-dot/lib/index.js
  packages/cli/test/nodejs-handler-filename-with-dot/my.lambda.js
  packages/cli/test/nodejs-handler-filename-with-dot/package.json
  packages/cli/test/nodejs-handler-filename-with-dot/sst.json
  packages/cli/test/nodejs-handler-relative-path/lambda-handler-relative-path.test.js
  packages/cli/test/nodejs-handler-relative-path/lambda.js
  packages/cli/test/nodejs-handler-relative-path/lib/index.js
  packages/cli/test/nodejs-handler-relative-path/nodejs-handler-relative-path/lambda.js
  packages/cli/test/nodejs-handler-relative-path/nodejs-handler-relative-path/lambda.js.map
  packages/cli/test/nodejs-handler-relative-path/package.json
  packages/cli/test/nodejs-handler-relative-path/sst.json
Labels: bug

#596 Fix for specifying handler with period in path
  packages/cli/scripts/start.js
  packages/cli/test/lambda-handler-relative/lambda-handler-relative.test.js
  packages/cli/test/lambda-handler-relative/lambda.js
  packages/cli/test/lambda-handler-relative/lib/index.js
  packages/cli/test/lambda-handler-relative/package.json
  packages/cli/test/lambda-handler-relative/sst.json
Labels: bug

#613 StaticSite: check path and buildOutput exist on build
  packages/resources/src/StaticSite.ts
  packages/resources/test/StaticSite.test.ts
Labels: bug

#616 sst start: print descriptive error message for handler not found
  packages/cli/scripts/start.js
Labels: enhancement

#618 Api: add support for HTTP proxy routes
  packages/resources/src/Api.ts
  packages/resources/test/Api.test.ts
  www/docs/constructs/Api.md
Labels: enhancement

#619 Api: add trailing slash to custom domain url
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/src/util/apiGatewayV2Domain.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/WebSocketApi.test.ts
  www/docs/constructs/Api.md
Labels: bug

#620 Api: support $default catch-all route
  www/docs/constructs/Api.md
Labels: enhancement

#621 ApolloApi: create 1 Lambda handler for both GET and POST routes
  packages/cli/test/playground/lib/apollo-api-stack.ts
  packages/cli/test/playground/lib/index.ts
  packages/resources/src/Api.ts
  packages/resources/src/ApolloApi.ts
  packages/resources/test/ApolloApi.test.ts
Labels: enhancement
