Repository serverless-stack/sst, pull requests merged in 2021-04, with the labels that each got.

#284 Allow adding sst.Stack to a Stage
  packages/resources/src/Stack.ts
  packages/resources/test/Stack.test.ts
Labels: enhancement

#287 Allow configuring App wide default function properties
  packages/resources/src/Api.ts
  packages/resources/src/App.ts
  packages/resources/src/AppSyncApi.ts
  packages/resources/src/Function.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/AppSyncApi.test.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/Api.md
  www/docs/constructs/App.md
  www/docs/constructs/Function.md
  yarn.lock
Labels: enhancement

#288 Add more logging for cdk deploy
  packages/core/index.js
Labels: skip changelog

#290 Support Cloudformation deploy strategy
  packages/core/index.js
Labels: skip changelog

#294 Log status and response latency as numbers in access log
  packages/resources/src/Api.ts
  packages/resources/test/Api.test.ts
Labels: bug

#297 Adding more context to CLI options
  packages/cli/bin/scripts.js
  www/docs/packages/cli.md
Labels: documentation

#301 Add support for Python runtime
  packages/cli/scripts/start.js
  packages/cli/scripts/util/Watcher.js
  packages/cli/scripts/util/bootstrap.js
  packages/cli/scripts/util/bootstrap.py
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/base-python/.gitignore
  packages/cli/test/base-python/lib/index.js
  packages/cli/test/base-python/package.json
  packages/cli/test/base-python/src-pip/handler.py
  packages/cli/test/base-python/src-pip/requirements.txt
  packages/cli/test/base-python/src-pipenv/Pipfile
  packages/cli/test/base-python/src-pipenv/Pipfile.lock
  packages/cli/test/base-python/src-pipenv/handler.py
  packages/cli/test/base-python/src-pipenv/sub/handler.py
  packages/cli/test/base-python/src-poetry/README.rst
  packages/cli/test/base-python/src-poetry/handler.py
  packages/cli/test/base-python/src-poetry/poetry.lock
  packages/cli/test/base-python/src-poetry/pyproject.toml
  packages/cli/test/base-python/src-poetry/src_poetry/__init__.py
  packages/cli/test/base-python/src-poetry/tests/__init__.py
  packages/cli/test/base-python/src-poetry/tests/test_src_poetry.py
  packages/cli/test/base-python/sst.json
  packages/cli/test/helpers/run-bootstrap.js
  packages/core/index.js
  packages/create-serverless-stack/bin/index.js
  packages/create-serverless-stack/templates/python/.template.gitignore
  packages/create-serverless-stack/templates/python/README.template.md
  packages/create-serverless-stack/templates/python/lib/%stack-name.PascalCased%.template.js
  packages/create-serverless-stack/templates/python/lib/index.template.js
  packages/create-serverless-stack/templates/python/package.template.json
  packages/create-serverless-stack/templates/python/src/lambda.py
  packages/create-serverless-stack/templates/python/sst.template.json
  packages/create-serverless-stack/templates/python/test/%stack-name.PascalCased%.test.template.js
  packages/resources/assets/python/Dockerfile
  packages/resources/assets/python/Dockerfile.dependencies
  packages/resources/assets/stub/index.js
  packages/resources/assets/stub/package.json
  packages/resources/assets/stub/yarn.lock
  packages/resources/bin/create-stub-zip.js
  packages/resources/package.json
  packages/resources/src/Function.ts
  packages/resources/src/util/builder.ts
  packages/resources/src/util/goBuilder.ts
  packages/resources/src/util/nodeBuilder.ts
  packages/resources/src/util/python/bundling.ts
  packages/resources/src/util/pythonBuilder.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/Function.md
  www/docs/installation.md
  www/docs/packages/create-serverless-stack.md
Labels: enhancement

#302 Correct some tiny typos
  www/docs/deploying-your-app.md
Labels: documentation

#298 Fixing docs related issues
  packages/cli/bin/scripts.js
  www/docs/about.md
  www/docs/constructs/Api.md
  www/docs/constructs/ApolloApi.md
  www/docs/constructs/App.md
  www/docs/constructs/AppSyncApi.md
  www/docs/constructs/Bucket.md
  www/docs/constructs/Function.md
  www/docs/constructs/Table.md
  www/docs/installation.md
  www/docs/live-lambda-development.md
  www/docs/migrating-from-serverless-framework.md
  www/docs/packages/cli.md
  www/docs/working-locally.md
Labels: documentation

#306 Skip bundling Lambda function on remove command
  packages/cli/scripts/remove.js
  packages/core/index.js
  packages/resources/src/Function.ts
Labels: bug

#304 Add descriptive error on when defaultFunctionProps is configured and a route is a Function instance
  packages/resources/src/Api.ts
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
Labels: skip changelog

#303 Support default permissions for Functions
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/Api.md
  www/docs/constructs/ApiGatewayV1Api.md
  www/docs/constructs/App.md
  www/docs/constructs/Function.md
Labels: enhancement

#307 Allow passing in short stack names to deploy and remove specific stacks
  packages/cli/scripts/deploy.js
  packages/cli/scripts/remove.js
Labels: enhancement

#308 Update CDK to 1.98.0
  packages/cli/package.json
  packages/cli/test/base-go/package.json
  packages/cli/test/base-python/package.json
  packages/cli/test/base-ts/package.json
  packages/cli/test/base/package.json
  packages/cli/test/bootstrap/package.json
  packages/cli/test/config/package.json
  packages/cli/test/context/package.json
  packages/cli/test/eslint-lambda-override-eslintrc/package.json
  packages/cli/test/go-build/package.json
  packages/cli/test/jest-ts/package.json
  packages/cli/test/jest/package.json
  packages/cli/test/lambda-override-tsconfig/package.json
  packages/cli/test/nodejs-build-bundle-copyfiles/package.json
  packages/cli/test/nodejs-build-bundle-externalmodules/package.json
  packages/cli/test/nodejs-build-bundle-loader/package.json
  packages/cli/test/nodejs-build-bundle-no-srcpath/package.json
  packages/cli/test/nodejs-build-bundle-nodemodules/package.json
  packages/cli/test/nodejs-build-bundle-srcpath/package.json
  packages/cli/test/nodejs-build-no-bundle-no-srcpath/package.json
  packages/cli/test/nodejs-build-no-bundle-srcpath/package.json
  packages/cli/test/playground/package.json
  packages/cli/test/rest-api-auth-cognito/package.json
  packages/cli/test/stack-no-prefix/package.json
  packages/cli/test/start-base/package.json
  packages/cli/test/start-demo/package.json
  packages/cli/test/start-guide/package.json
  packages/cli/test/start-handler-sync-async-cases/package.json
  packages/cli/test/start-no-src-path/package.json
  packages/cli/test/template-app-ts/package.json
  packages/cli/test/template-app/package.json
  packages/cli/test/watcher/package.json
  packages/core/package.json
  packages/resources/package.json
  packages/resources/src/Api.ts
  packages/resources/test/Api.test.ts
  yarn.lock
Labels: enhancement

#309 Add helper for AppSync CloudFormation error: "Only one resolver is allowed per field."
  packages/cli/test/playground/lib/app-sync-api-stack.ts
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/package-lock.json
  packages/cli/test/playground/package.json
  packages/cli/test/playground/src/appsync/lambda.ts
  packages/cli/test/playground/src/appsync/schema.graphql
  packages/core/errorHelpers.js
  packages/core/index.js
Labels: skip changelog

#310 Fix error on sst remove
  packages/resources/src/App.ts
  packages/resources/src/Function.ts
Labels: skip changelog

#312 Fixing cdk imports in docs
  www/docs/constructs/Api.md
  www/docs/constructs/ApiGatewayV1Api.md
  www/docs/constructs/AppSyncApi.md
  www/docs/constructs/Auth.md
  www/docs/constructs/Bucket.md
  www/docs/constructs/Cron.md
  www/docs/constructs/Function.md
  www/docs/constructs/Queue.md
  www/docs/constructs/Stack.md
  www/docs/constructs/Table.md
  www/docs/constructs/Topic.md
Labels: documentation

#315 Showing example with sst import in constructs
  www/docs/constructs/Api.md
  www/docs/constructs/ApiGatewayV1Api.md
  www/docs/constructs/ApolloApi.md
  www/docs/constructs/AppSyncApi.md
  www/docs/constructs/Auth.md
  www/docs/constructs/Bucket.md
  www/docs/constructs/Cron.md
  www/docs/constructs/Function.md
  www/docs/constructs/Queue.md
  www/docs/constructs/Table.md
  www/docs/constructs/Topic.md
Labels: documentation

#314 Add WebSocketApi construct
  README.md
  packages/cli/test/playground/cdk.context.json
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/lib/websocket-api-stack.ts
  packages/cli/test/playground/src/lambda.ts
  packages/core/errorHelpers.js
  packages/resources/src/Api.ts
  packages/resources/src/WebSocketApi.ts
  packages/resources/src/index.ts
  packages/resources/src/util/apiGatewayV2AccessLog.ts
  packages/resources/src/util/apiGatewayV2Domain.ts
  packages/resources/src/util/permission.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/Function.test.ts
  packages/resources/test/WebSocketApi.test.ts
  packages/resources/test/apiGatewayV2AccessLog.test.ts
  www/docs/constructs/Function.md
  www/docs/constructs/WebSocketApi.md
  www/sidebars.js
Labels: enhancement

#316 Fix sst remove error for nodejs14.x runtime
  packages/cli/test/playground/lib/websocket-api-stack.ts
  packages/resources/src/Function.ts
Labels: bug

#320 Reviewing the WebSocket API docs
  www/docs/constructs/Api.md
  www/docs/constructs/WebSocketApi.md
  www/docs/migrating-from-cdk.md
Labels: documentation

#321 Allow customizing the UserPool and the IdentityPool in the Auth construct
  packages/resources/src/Auth.ts
  packages/resources/test/Auth.test.ts
  www/docs/constructs/Auth.md
Labels: enhancement

#322 Add url and customDomainUrl properties to all Api constructs
  packages/cli/test/playground/lib/api-stack.ts
  packages/cli/test/playground/lib/index.ts
  packages/resources/src/Api.ts
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/src/AppSyncApi.ts
  packages/resources/src/WebSocketApi.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
  packages/resources/test/AppSyncApi.test.ts
  www/docs/constructs/Api.md
  www/docs/constructs/ApiGatewayV1Api.md
  www/docs/constructs/AppSyncApi.md
Labels: enhancement

#323 Allow importing user pool and user pool client for the Auth construct
  packages/resources/src/Api.ts
  packages/resources/src/Auth.ts
  packages/resources/test/Auth.test.ts
  www/docs/constructs/Auth.md
Labels: skip changelog

#325 Fix ApiGatewayV1Api CUSTOM authorization type override by NONE
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
Labels: bug

#328 Fix typo on .gitignore file name in documentation
  www/docs/migrating-from-serverless-framework.md
Labels: documentation

#330 Adding docs on debugging tests in VS Code
  www/docs/debugging-with-vscode.md
  www/static/img/screens/vs-code-debug-sst-start.png
  www/static/img/screens/vs-code-debug-sst-tests.png
  www/static/img/screens/vs-code-run-and-debug-tab.png
Labels: documentation

#331 Support callback format for App.setDefaultFunctionProps
  packages/resources/src/App.ts
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/App.md
Labels: enhancement

#335 Load dotenv inside CDK process
  packages/cli/assets/cdk-wrapper/run.js
  packages/cli/bin/scripts.js
  packages/cli/scripts/start.js
  packages/cli/test/is-local/is-local.test.js
  packages/cli/test/is-local/lib/index.js
  packages/cli/test/is-local/package.json
  packages/cli/test/is-local/sst.json
  packages/cli/test/playground/package.json
  packages/resources/test/Function.test.ts
  www/docs/working-locally.md
  yarn.lock
Labels: skip changelog

#339 Tiny typos
  www/docs/working-locally.md
Labels: documentation

#340 Expanding the environment variable doc
  www/docs/environment-variables.md
  www/docs/working-locally.md
  www/sidebars.js
Labels: documentation

#343 Updating templates to use api.url
  packages/create-serverless-stack/templates/go/lib/%stack-name.PascalCased%.template.js
  packages/create-serverless-stack/templates/javascript/lib/%stack-name.PascalCased%.template.js
  packages/create-serverless-stack/templates/python/lib/%stack-name.PascalCased%.template.js
  packages/create-serverless-stack/templates/typescript/lib/%stack-name.PascalCased%.template.ts
Labels: enhancement

#345 Handle large Lambda payload with sst start
  packages/cli/assets/cdk-wrapper/run.js
  packages/cli/assets/debug-stack/lib/DebugStack.js
  packages/cli/package.json
  packages/cli/scripts/start.js
  packages/cli/scripts/util/LambdaRuntimeServer.js
  packages/cli/scripts/util/bootstrap.js
  packages/cli/test/bootstrap/bootstrap.test.js
  packages/cli/test/helpers/run-bootstrap.js
  packages/resources/assets/stub/index.js
  packages/resources/src/App.ts
  packages/resources/src/Function.ts
Labels: bug

#347 Truncate Lambda response shown in the terminal
  packages/cli/lib/object.js
  packages/cli/scripts/start.js
  packages/cli/test/lib/lib.test.js
  packages/cli/test/lib/package.json
  packages/resources/src/App.ts
  packages/resources/src/Function.ts
Labels: enhancement

#346 Support defaultFunctionProps for Topic construct
  packages/resources/src/Topic.ts
  packages/resources/test/Topic.test.ts
  www/docs/constructs/Topic.md
Labels: enhancement

#349 Fix null payload issue for sst start
  packages/cli/lib/object.js
  packages/cli/test/lib/lib.test.js
Labels: bug

#350 Function doc line to reference default func props
  www/docs/constructs/Function.md
Labels: documentation

#352 Add snsSubscriptions property for Topic construct
  packages/resources/src/Topic.ts
  packages/resources/test/Topic.test.ts
  www/docs/constructs/Topic.md
Labels: enhancement

#353 Redeploy infrastructure changes without restarting sst start
  packages/cli/bin/scripts.js
  packages/cli/lib/array.js
  packages/cli/scripts/deploy.js
  packages/cli/scripts/start.js
  packages/cli/scripts/util/Watcher.js
  packages/cli/scripts/util/WatcherCdkState.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/scripts/util/processHelpers.js
  packages/cli/test/playground/lib/api-stack.ts
  packages/cli/test/watcher-cdk-state/package.json
  packages/cli/test/watcher-cdk-state/watcher-cdk-state.test.js
  packages/cli/test/watcher/watcher.test.js
  packages/core/cancelablePromise.js
  packages/core/index.js
Labels: enhancement

#355 sst start skip CloudFormation deployment if templates not changed
  packages/cli/bin/scripts.js
  packages/cli/scripts/start.js
  packages/cli/scripts/util/Watcher.js
  packages/cli/scripts/util/WatcherCdkState.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/watcher-cdk-state/watcher-cdk-state.test.js
Labels: enhancement

#357 Stack: validate stack output is not undefined
  packages/resources/src/Stack.ts
  packages/resources/src/Topic.ts
  packages/resources/test/Stack.test.ts
  packages/resources/test/Topic.test.ts
Labels: enhancement
