Repository serverless-stack/sst, pull requests merged in 2021-12, with the labels that each got.

#1102 sst start: default CloudFormation rollback behavior to true
  packages/cli/bin/scripts.js
  packages/core/src/index.js
  www/docs/packages/cli.md
Labels: enhancement

#1103 Script: fix response too long error
  packages/cli/test/playground/lib/api-extra-routes-stack.ts
  packages/cli/test/playground/lib/index.ts
  packages/resources/src/Script/index.ts
Labels: bug

#1104 Make deployId public
  packages/resources/src/StaticSite.ts
Labels: bug

#1110 Docs: Add a missing new line in code sample
  www/docs/environment-variables.md
Labels: documentation

#1119 Docs: Removed redundant config for Thundra integration
  www/docs/monitoring-your-app-in-prod.md
Labels: documentation

#1126 Function: allow setDefaultFunctionProps before Functions are created
  packages/resources/src/App.ts
  packages/resources/src/Stack.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/App.md
  www/docs/constructs/Stack.md
Labels: enhancement

#1125 Function: allow imported IConstructs in attachPermissions
  packages/resources/src/util/permission.ts
  packages/resources/test/Function.test.ts
  www/docs/util/Permissions.md
Labels: enhancement

#1123 Fixed bug with adding multiple topic subscribers in same stack
  packages/resources/src/Topic.ts
  packages/resources/test/Topic.test.ts
Labels: bug

#1129 Pin version in update test
  .github/workflows/ci.yml
  packages/cli/test/update/update.test.js
Labels: bug

#1128 Script create user function protected
  packages/resources/src/Script.ts
Labels: internal

#1143 cli: respect aws cli region if region is not provided
  packages/cli/assets/debug-stack/bin/index.js
  packages/cli/assets/debug-stack/lib/DebugStack.js
  packages/cli/bin/scripts.js
  packages/cli/scripts/util/ConstructsState.js
  packages/resources/src/App.ts
Labels: bug

#1146 Queue: cannot call addConsumer multiple times from the same scope
  packages/resources/src/Queue.ts
  packages/resources/test/Queue.test.ts
Labels: bug

#1149 Fix crash when function not found
  packages/cli/scripts/start.js
Labels: bug

#1148 Fixed empty functions file
  packages/core/src/state/function.ts
Labels: bug

#1150 Fix debug bucket
  packages/cli/scripts/start.js
Labels: bug

#1152 Fix issue with python bundling
  packages/core/src/runtime/handler/python.ts
Labels: bug

#1092 Block public access for DebugStack S3 bucket
  packages/cli/assets/debug-stack/lib/DebugStack.js
Labels: enhancement

#1162 Clear artifacts per function
  packages/core/src/runtime/handler/dotnet.ts
  packages/core/src/runtime/handler/go.ts
  packages/core/src/runtime/handler/node.ts
  packages/core/src/state/function.ts
Labels: bug

#1164 Various performance fixes
  packages/cli/scripts/start.js
Labels: bug

#1171 Fix a typo in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1172 Function: functionName takes callback
  packages/resources/.gitignore
  packages/resources/src/Function.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/Function.md
Labels: enhancement

#1173 Bucket: allow multiple addNotifications calls within the same scope
  packages/resources/src/Bucket.ts
  packages/resources/test/Bucket.test.ts
  packages/resources/test/Topic.test.ts
Labels: bug

#1167 Fix esbuild treating warnings as errors
  .github/workflows/ci.yml
  packages/core/src/runtime/handler/node.ts
Labels: bug

#1178 Fix reload functionBuilder
  packages/cli/scripts/start.js
Labels: bug

#1200 Display last update time on docs
  www/docusaurus.config.js
Labels: documentation
