Repository serverless-stack/sst, pull requests merged in 2021-10, with the labels that each got.

#871 NextjsSite: support deploying to all regions
  packages/cli/test/playground-region/cdk.context.json
  packages/cli/test/playground-region/lib/api-stack.js
  packages/cli/test/playground-region/lib/index.js
  packages/cli/test/playground-region/lib/nextjs-site-stack.js
  packages/cli/test/playground-region/package.json
  packages/cli/test/playground-region/src/edge/lambda.js
  packages/cli/test/playground-region/src/lambda.js
  packages/cli/test/playground-region/src/sites/nextjs/.gitignore
  packages/cli/test/playground-region/src/sites/nextjs/README.md
  packages/cli/test/playground-region/src/sites/nextjs/components/date.js
  packages/cli/test/playground-region/src/sites/nextjs/components/layout.js
  packages/cli/test/playground-region/src/sites/nextjs/components/layout.module.css
  packages/cli/test/playground-region/src/sites/nextjs/lib/posts.js
  packages/cli/test/playground-region/src/sites/nextjs/next.config.js
  packages/cli/test/playground-region/src/sites/nextjs/next.config.original.1633069454296.js
  packages/cli/test/playground-region/src/sites/nextjs/package-lock.json
  packages/cli/test/playground-region/src/sites/nextjs/package.json
  packages/cli/test/playground-region/src/sites/nextjs/pages/404.js
  packages/cli/test/playground-region/src/sites/nextjs/pages/_app.js
  packages/cli/test/playground-region/src/sites/nextjs/pages/api/hello.js
  packages/cli/test/playground-region/src/sites/nextjs/pages/api/preview.js
  packages/cli/test/playground-region/src/sites/nextjs/pages/csr.js
  packages/cli/test/playground-region/src/sites/nextjs/pages/index.js
  packages/cli/test/playground-region/src/sites/nextjs/pages/isr.js
  packages/cli/test/playground-region/src/sites/nextjs/pages/posts/[id].js
  packages/cli/test/playground-region/src/sites/nextjs/pages/ssg-fallback-true/[id].js
  packages/cli/test/playground-region/src/sites/nextjs/pages/ssg-preview/[id].js
  packages/cli/test/playground-region/src/sites/nextjs/pages/ssr-not-found.js
  packages/cli/test/playground-region/src/sites/nextjs/pages/ssr-redirect.js
  packages/cli/test/playground-region/src/sites/nextjs/pages/ssr.js
  packages/cli/test/playground-region/src/sites/nextjs/posts/pre-rendering.md
  packages/cli/test/playground-region/src/sites/nextjs/posts/ssg-ssr.md
  packages/cli/test/playground-region/src/sites/nextjs/public/favicon.ico
  packages/cli/test/playground-region/src/sites/nextjs/public/images/profile.jpg
  packages/cli/test/playground-region/src/sites/nextjs/styles/global.css
  packages/cli/test/playground-region/src/sites/nextjs/styles/utils.module.css
  packages/cli/test/playground-region/sst.json
  packages/resources/assets/NextjsSite/edge-lambda-stub/index.js
  packages/resources/assets/NextjsSite/site-stub/index.html
  packages/resources/package.json
  packages/resources/src/NextjsSite.ts
  packages/resources/src/nextjs-site/cross-region-helper.ts
  packages/resources/src/nextjs-site/custom-resource/cfn-response.ts
  packages/resources/src/nextjs-site/custom-resource/edge-lambda-version.ts
  packages/resources/src/nextjs-site/custom-resource/edge-lambda.ts
  packages/resources/src/nextjs-site/custom-resource/s3-bucket.ts
  packages/resources/src/nextjs-site/custom-resource/util.ts
  packages/resources/test/NextjsSite.test.ts
  yarn.lock
Labels: enhancement

#877 NextjsSite: fix alias already exist error on subsequent deploys
  packages/cli/test/playground-region/src/sites/nextjs/pages/index.js
  packages/resources/src/nextjs-site/custom-resource/edge-lambda-version.ts
Labels: bug

#878 Update CDK version to 1.125.0
  packages/cli/package.json
  packages/cli/test/base-dotnet/package.json
  packages/cli/test/base-go/package.json
  packages/cli/test/base-python/package.json
  packages/cli/test/base-ts/package.json
  packages/cli/test/base-tsx/package.json
  packages/cli/test/base/package.json
  packages/cli/test/config-main-js/package.json
  packages/cli/test/config-main-ts/package.json
  packages/cli/test/config/package.json
  packages/cli/test/context/package.json
  packages/cli/test/dotenv/package.json
  packages/cli/test/dotnet-bootstrap/package.json
  packages/cli/test/dotnet-build/package.json
  packages/cli/test/eslint-lambda-override-eslintrc/package.json
  packages/cli/test/go-build/package.json
  packages/cli/test/is-local/package.json
  packages/cli/test/jest-ts/package.json
  packages/cli/test/jest/package.json
  packages/cli/test/lambda-override-tsconfig/package.json
  packages/cli/test/lambda-watcher-state/package.json
  packages/cli/test/nodejs-bootstrap/package.json
  packages/cli/test/nodejs-build-bundle-copyfiles/package.json
  packages/cli/test/nodejs-build-bundle-esbuildconfig/package.json
  packages/cli/test/nodejs-build-bundle-externalmodules/package.json
  packages/cli/test/nodejs-build-bundle-loader/package.json
  packages/cli/test/nodejs-build-bundle-no-srcpath/package.json
  packages/cli/test/nodejs-build-bundle-nodemodules/package.json
  packages/cli/test/nodejs-build-bundle-srcpath/package.json
  packages/cli/test/nodejs-build-no-bundle-no-srcpath/package.json
  packages/cli/test/nodejs-build-no-bundle-srcpath/package.json
  packages/cli/test/nodejs-handler-filename-with-dot/package.json
  packages/cli/test/nodejs-handler-relative-path/package.json
  packages/cli/test/playground/package.json
  packages/cli/test/remove/package.json
  packages/cli/test/rest-api-auth-cognito/package.json
  packages/cli/test/stack-no-prefix/package.json
  packages/cli/test/start-base/package.json
  packages/cli/test/start-demo/package.json
  packages/cli/test/start-guide/package.json
  packages/cli/test/start-handler-sync-async-cases/package.json
  packages/cli/test/start-no-src-path/package.json
  packages/cli/test/template-app-ts/package.json
  packages/cli/test/template-app/package.json
  packages/cli/test/update/package.json
  packages/core/package.json
  packages/resources/package.json
  yarn.lock
Labels: enhancement

#885 Ensure esbuild config is deep copied
  packages/resources/src/util/nodeBuilder.ts
Labels: bug

#811 Add EventBridge message mapping
  www/docs/constructs/EventBus.md
Labels: documentation

#889 Docs: Update faq.md
  www/docs/faq.md
Labels: documentation

#887 Function: Minify nodejs bundle
  packages/resources/src/util/nodeBuilder.ts
Labels: enhancement

#891 Ensure customConfig is deep cloned to avoid side affects
  packages/cli/scripts/util/cdkHelpers.js
Labels: bug

#894 [Documentation] Update links to Epsagon docs
  www/docs/monitoring-your-app-in-prod.md
Labels: documentation

#896 CLI: Skip asking for stage on test command
  packages/cli/bin/scripts.js
  www/docs/packages/cli.md
Labels: bug
