Repository serverless-stack/sst, pull requests merged in 2022-09, with the labels that each got.

#2016 Table: support event filtering for stream consumer
  .changeset/eighty-buses-laugh.md
  packages/resources/src/Table.ts
  packages/resources/test/Table.test.ts
  www/docs/constructs/Table.about.md
Labels: enhancement

#2022 Cognito: fix calling attachPermissions from different stacks override previous permissions
  .changeset/tender-shrimps-exercise.md
  packages/resources/src/Cognito.ts
  packages/resources/test/Cognito.test.ts
Labels: bug

#2024 Parallel build
  .changeset/six-spoons-jump.md
  .changeset/snapshot
  packages/cli/assets/cdk-wrapper/run.mjs
  packages/core/src/defer-builder/index.ts
  packages/core/src/index.ts
  packages/core/src/runtime/handler/definition.ts
  packages/core/src/runtime/handler/dotnet.ts
  packages/core/src/runtime/handler/go.ts
  packages/core/src/runtime/handler/index.ts
  packages/core/src/runtime/handler/java.ts
  packages/core/src/runtime/handler/node.ts
  packages/core/src/runtime/handler/python.ts
  packages/resources/src/App.ts
  packages/resources/src/Function.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
  packages/resources/test/AppSyncApi.test.ts
  packages/resources/test/Bucket.test.ts
  packages/resources/test/Cognito.test.ts
  packages/resources/test/Cron.test.ts
  packages/resources/test/EventBus.test.ts
  packages/resources/test/Function.test.ts
  packages/resources/test/GraphQLApi.test.ts
  packages/resources/test/KinesisStream.test.ts
  packages/resources/test/Queue.test.ts
  packages/resources/test/Script.test.ts
  packages/resources/test/Table.test.ts
  packages/resources/test/Topic.test.ts
  packages/resources/test/WebSocketApi.test.ts
Labels: enhancement

#2033 Fix missing stack metadata
  .changeset/three-ants-buy.md
  packages/resources/src/Stack.ts
Labels: bug

#2035 Function: fix nodeModules not bundled
  .changeset/new-yaks-pay.md
  packages/core/src/runtime/handler/node.ts
Labels: bug

#2056 Function: fix parallel build fails in CI environment
  .changeset/lemon-colts-switch.md
  packages/core/src/defer-builder/index.ts
Labels: bug

#2057 Update CDK to v2.39.1
  .changeset/silver-sheep-wonder.md
  packages/cli/package.json
  packages/core/package.json
  packages/resources/package.json
  packages/resources/test/AppSyncApi.test.ts
  yarn.lock
Labels: enhancement

#2063 Updating to RDS and DynamoDB starter to Kysely codegen
  .changeset/slimy-lemons-hear.md
  packages/create-sst/bin/presets/base/javascript/templates/package.json
  packages/create-sst/bin/presets/graphql/basic/preset.mjs
  packages/create-sst/bin/presets/graphql/basic/templates/web/index.html
  packages/create-sst/bin/presets/graphql/basic/templates/web/public/favicon.ico
  packages/create-sst/bin/presets/graphql/basic/templates/web/public/share.png
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/components/Button.css.ts
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/components/Button.tsx
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/components/Empty.css.ts
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/components/Empty.tsx
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/components/Loading.css.ts
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/components/Loading.tsx
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/components/Navbar.css.ts
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/components/Navbar.tsx
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/index.css.ts
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/main.tsx
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/pages/Article.css.ts
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/pages/Article.tsx
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/pages/Home.css.ts
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/pages/Home.tsx
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/urql.ts
  packages/create-sst/bin/presets/graphql/basic/templates/web/src/vars.css.ts
  packages/create-sst/bin/presets/graphql/basic/templates/web/vite.config.ts
  packages/create-sst/bin/presets/graphql/dynamo/templates/services/core/article.ts
  packages/create-sst/bin/presets/graphql/dynamo/templates/services/functions/graphql/types/article.ts
  packages/create-sst/bin/presets/graphql/dynamo/templates/web/src/main.tsx
  packages/create-sst/bin/presets/graphql/dynamo/templates/web/src/pages/Article.tsx
  packages/create-sst/bin/presets/graphql/dynamo/templates/web/src/urql.ts
  packages/create-sst/bin/presets/graphql/rds/preset.mjs
  packages/create-sst/bin/presets/graphql/rds/templates/services/core/article.ts
  packages/create-sst/bin/presets/graphql/rds/templates/services/functions/graphql/types/article.ts
  packages/create-sst/bin/presets/graphql/rds/templates/web/src/main.tsx
  packages/create-sst/bin/presets/graphql/rds/templates/web/src/pages/Article.tsx
  www/docs/learn/queries-and-mutations.md
  www/docs/learn/write-to-the-database.md
Labels: enhancement

#2072 Cli: fix functions restarted twice on secrets set
  .changeset/many-balloons-clap.md
  packages/cli/scripts/start.mjs
  packages/core/assets/bootstrap/cdk-app/custom-resources/cfn-response.mjs
  packages/core/assets/bootstrap/cdk-app/custom-resources/stack-metadata.mjs
  packages/core/assets/bootstrap/cdk-app/custom-resources/util.mjs
  packages/core/src/function-config/index.ts
Labels: bug

#2070 Replace "\n" by ";" on custom-resoruces build.
  .changeset/new-pugs-dream.md
  packages/cli2/src/stacks/build.ts
  packages/core/src/runtime/handler/node.ts
  packages/core/src/stacks/build.ts
  packages/resources/support/bridge/build.mjs
  packages/resources/support/custom-resources/build.mjs
Labels: bug

#2076 Bucket: support notifications on imported S3 Buckets
  .changeset/wicked-birds-boil.md
  packages/resources/src/Bucket.ts
  packages/resources/test/Bucket.test.ts
  www/docs/advanced/importing-resources.md
Labels: enhancement

#2071 Adding new What is SST chapter
  www/docs/architecture.md
  www/docs/introduction.md
  www/docs/what-is-sst.md
  www/sidebars.js
Labels: documentation

#2028 Long running tasks
  .changeset/silver-otters-switch.md
  packages/core/src/runtime/ws.ts
  packages/node/job/index.d.ts
  packages/node/job/index.js
  packages/node/package.json
  packages/node/src/job/index.ts
  packages/resources/package.json
  packages/resources/src/App.ts
  packages/resources/src/Config.ts
  packages/resources/src/Function.ts
  packages/resources/src/Job.ts
  packages/resources/src/index.ts
  packages/resources/src/util/permission.ts
  packages/resources/support/job-invoker/build.mjs
  packages/resources/support/job-invoker/index.ts
  packages/resources/test/Function.test.ts
  www/docs/constructs/App.tsdoc.md
  www/docs/constructs/Bucket.tsdoc.md
  www/docs/constructs/Job.about.md
  www/docs/constructs/Job.md
  www/docs/constructs/NextjsSite.tsdoc.md
  www/docs/constructs/Permissions.md
  www/docs/constructs/RemixSite.tsdoc.md
  www/docs/constructs/StaticSite.tsdoc.md
  www/docs/constructs/ViteStaticSite.tsdoc.md
  www/docs/environment-variables.md
  www/docs/long-running-jobs.md
  www/docs/packages/node.md
  www/generate.mjs
  www/sidebars.js
  www/static/img/long-running-jobs/sst-console-job.png
  yarn.lock
Labels: enhancement

#2084 Await runAfterBundling
  packages/core/src/runtime/handler/node.ts
Labels: bug

#2090 Job: fix environment not added
  .changeset/five-turkeys-rush.md
  packages/resources/src/Job.ts
  packages/resources/test/Job.test.ts
Labels: bug

#2046 Remove resource properties not supported in GovCloud
  .changeset/strong-mugs-film.md
  packages/resources/src/App.ts
  packages/resources/test/App.test.ts
Labels: bug

#2109 StaticSite: handle Gatsby build's 404.html folder
  .changeset/little-peas-camp.md
  packages/resources/assets/BaseSite/custom-resource/s3-upload.py
Labels: bug

#2111 Queue: support imported consumer function
  .changeset/wise-swans-tell.md
  packages/resources/src/Queue.ts
  packages/resources/test/Queue.test.ts
Labels: enhancement
