Repository serverless-stack/sst, pull requests merged in 2022-04, with the labels that each got.

#1597 Fix infinite rebuild loop (backport)
  packages/core/src/cli/StacksBuilder.ts
Labels: bug

#1596 Fix infinite rebuild loop
  packages/core/src/cli/StacksBuilder.ts
Labels: bug

#1603 Cli: stack xxxx does not exist error on successful deploy
  packages/cli/bin/scripts.js
  packages/core/src/aws-sdk/index.ts
Labels: bug

#1604 Cli: stack xxxx does not exist error on successful deploy
  packages/cli/bin/scripts.js
  packages/core/src/aws-sdk/index.ts
Labels: bug

#1605 Cli: fix missing region in config error
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
Labels: bug

#1606 Cli: fix missing region in config error
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
Labels: bug

#1608 Function: Add architecture prop
  packages/console/src/App/Stage/Functions/Detail.tsx
  packages/resources/src/Function.ts
Labels: enhancement

#1617 Added Google Login to user pool example
  examples/api-oauth-google/.env
  examples/api-oauth-google/.gitignore
  examples/api-oauth-google/README.md
  examples/api-oauth-google/frontend/.gitignore
  examples/api-oauth-google/frontend/index.html
  examples/api-oauth-google/frontend/package.json
  examples/api-oauth-google/frontend/src/App.jsx
  examples/api-oauth-google/frontend/src/favicon.svg
  examples/api-oauth-google/frontend/src/index.css
  examples/api-oauth-google/frontend/src/logo.svg
  examples/api-oauth-google/frontend/src/main.jsx
  examples/api-oauth-google/frontend/src/sst-env.d.ts
  examples/api-oauth-google/frontend/vite.config.js
  examples/api-oauth-google/package.json
  examples/api-oauth-google/src/private.js
  examples/api-oauth-google/src/public.js
  examples/api-oauth-google/sst.json
  examples/api-oauth-google/stacks/MyStack.js
  examples/api-oauth-google/stacks/index.js
  examples/api-oauth-google/test/MyStack.test.js
Labels: documentation

#1620 Fix cdk binary not found when pnpm is used
  packages/cli/scripts/cdk.js
  packages/core/src/index.ts
Labels: bug

#1623 WebSocketApi: keep authorizer id consistent with v0.x
  packages/resources/src/WebSocketApi.ts
Labels: bug

#1624 V1 apigateway authorizer
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
Labels: enhancement

#1626 Update CDK to 2.20.0
  packages/cli/package.json
  packages/cli/test/playground/package.json
  packages/cli/test/update-from-cdk-v1/package.json
  packages/cli/test/update-from-cdk-v2/package.json
  packages/core/package.json
  packages/resources/package.json
  yarn.lock
Labels: enhancement

#1553 Fix invalid typescript monorepo example name
  www/docs/advanced/monorepo-project-structure.md
Labels: documentation

#1632 Function: support configuring disk size
  packages/resources/src/Function.ts
  packages/resources/src/index.ts
  packages/resources/src/util/size.ts
  packages/resources/test/Function.test.ts
Labels: enhancement

#1630 Update docs UI
  www/docs/about.module.css
  www/docs/api.md
  www/docs/asynchronous-tasks.md
  www/docs/auth.md
  www/docs/cron-jobs.md
  www/docs/database.md
  www/docs/frontend.md
  www/docs/live-lambda-development.md
  www/docs/storage.md
  www/docusaurus.config.js
  www/src/css/custom.css
Labels: documentation

#1638 Added GitHub Login example
  examples/api-oauth-github/.env
  examples/api-oauth-github/.gitignore
  examples/api-oauth-github/README.md
  examples/api-oauth-github/frontend/.gitignore
  examples/api-oauth-github/frontend/index.html
  examples/api-oauth-github/frontend/package.json
  examples/api-oauth-github/frontend/src/App.jsx
  examples/api-oauth-github/frontend/src/favicon.svg
  examples/api-oauth-github/frontend/src/index.css
  examples/api-oauth-github/frontend/src/logo.svg
  examples/api-oauth-github/frontend/src/main.jsx
  examples/api-oauth-github/frontend/src/sst-env.d.ts
  examples/api-oauth-github/frontend/vite.config.js
  examples/api-oauth-github/package.json
  examples/api-oauth-github/src/private.js
  examples/api-oauth-github/src/public.js
  examples/api-oauth-github/src/token.js
  examples/api-oauth-github/src/user.js
  examples/api-oauth-github/sst.json
  examples/api-oauth-github/stacks/MyStack.js
  examples/api-oauth-github/stacks/index.js
  examples/api-oauth-github/test/MyStack.test.js
Labels: documentation

#1641 Bucket: lift cors settings
  .eslintignore
  packages/resources/src/Api.ts
  packages/resources/src/Bucket.ts
  packages/resources/src/util/apiGatewayV2Cors.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/Bucket.test.ts
Labels: enhancement

#1646 Cli: fix "stack does not exist" error for stacks with customized names
  packages/cli/scripts/start.js
Labels: bug

#1647 Cli: fix "stack does not exist" error for stacks with customized names
  packages/cli/scripts/start.js
Labels: bug

#1652 Cli: handle CDKToolkit bootstrap stack stuck in REVIEW_IN_PROGRESS
  packages/core/src/index.ts
Labels: enhancement

#1653 Cli: using aws-vault causes invalid credentials for boto3
  packages/cli/scripts/start.js
Labels: bug

#1664 AppSyncApi: support NONE data source
  packages/resources/src/AppSyncApi.ts
  packages/resources/test/AppSyncApi.test.ts
Labels: enhancement
