Repository serverless-stack/sst, pull requests merged in 2022-02, with the labels that each got.

#1324 Support GraphQL formatPayload callback
  packages/node/src/graphql.ts
Labels: enhancement

#1325 Updated RDS's construct metadata
  packages/resources/src/RDS.ts
Labels: skip changelog

#1326 Function: show helpful error message when esbuild plugin is not found
  packages/core/src/runtime/handler/node.ts
Labels: enhancement

#1322 Add console command + cloudwatch logs
  packages/cli/bin/scripts.js
  packages/cli/scripts/console.js
  packages/cli/scripts/start.js
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/lib/lambda-error-cases-stack.ts
  packages/cli/test/playground/src/lambda-error-cases/nodeErrors.js
  packages/cli/test/playground/src/lambda-error-cases/pythonErrors.py
  packages/console/public/favicon.svg
  packages/console/src/App/Stage/Buckets/index.tsx
  packages/console/src/App/Stage/Cognito/index.tsx
  packages/console/src/App/Stage/Functions/CWInvocation.tsx
  packages/console/src/App/Stage/Functions/Detail.tsx
  packages/console/src/App/Stage/Functions/index.tsx
  packages/console/src/App/Stage/Panel.tsx
  packages/console/src/components/Badge.tsx
  packages/console/src/components/Button.tsx
  packages/console/src/components/Logo.tsx
  packages/console/src/data/aws/function.ts
  packages/console/src/main.tsx
  packages/console/src/stitches.config.ts
  packages/core/src/local/router.ts
  packages/core/src/local/server.ts
  packages/core/src/runtime/handler/node.ts
  packages/core/src/runtime/server.ts
  packages/node/src/graphql.ts
  www/docs/packages/cli.md
Labels: enhancement

#1303 Add support for AWS GovCloud
  packages/cli/assets/debug-stack/lib/DebugStack.js
  packages/resources/src/Stack.ts
Labels: bug

#1335 Api: access log retention takes RetentionDays format
  packages/resources/bin/copy-rds-migrator.js
  packages/resources/src/util/apiGatewayV2AccessLog.ts
  packages/resources/test/Api.test.ts
  www/docs/constructs/Api.md
  www/docs/constructs/WebSocketApi.md
Labels: enhancement

#1340 Do not ignore entire stacks folder for function watcher
  packages/cli/scripts/start.js
  packages/core/src/runtime/watcher.ts
Labels: bug

#1336 Generate truly unique function local ids
  packages/resources/src/Function.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
  packages/resources/test/Function.test.ts
  packages/resources/test/WebSocketApi.test.ts
Labels: bug

#1329 Add monitoring instructions for New Relic
  www/docs/advanced/monitoring.md
Labels: documentation

#1339 Cli: support AWS credentials with assume role and MFA
  packages/cli/bin/scripts.js
  packages/cli/test/helpers/run-build-command.js
  packages/cli/test/helpers/run-cdk-command.js
  packages/cli/test/playground/lib/lambda-error-cases-stack.ts
  packages/core/src/aws-sdk/aws-sdk-inifile.ts
  packages/core/src/aws-sdk/awscli-compatible.ts
  packages/core/src/aws-sdk/index.ts
  packages/core/src/aws-sdk/sdk_ini_file.ts
  packages/core/src/index.ts
Labels: enhancement

#1343 ViteStaticSite: generate types definition for JS projects
  packages/resources/src/ViteStaticSite.ts
  packages/resources/test/ViteStaticSite.test.ts
  packages/resources/test/vite-static-site/.gitignore
  packages/resources/test/vite-static-site/build/index.html
  packages/resources/test/vite-static-site/error.html
  packages/resources/test/vite-static-site/index.html
  packages/resources/test/vite-static-site/package.json
  packages/resources/test/vite-static-site/ts-site/.gitignore
  packages/resources/test/vite-static-site/ts-site/build/index.html
  packages/resources/test/vite-static-site/ts-site/error.html
  packages/resources/test/vite-static-site/ts-site/index.html
  packages/resources/test/vite-static-site/ts-site/package.json
  packages/resources/test/vite-static-site/ts-site/tsconfig.json
Labels: enhancement

#1345 RDS: do not trigger migration scripts on restarting sst start
  packages/cli/test/playground/lib/rds-stack.ts
  packages/resources/src/RDS.ts
Labels: skip changelog

#1346 Use ViteStaticSite for Svelte example
  examples/svelte-app/package.json
  examples/svelte-app/stacks/MyStack.js
Labels: skip changelog

#1349 Cli: fix sst.json stage deprecation docs link
  packages/cli/bin/scripts.js
Labels: skip changelog

#1348 Auth: add custom email and sms sender triggers
  packages/resources/src/Auth.ts
Labels: enhancement

#1342 Auth Console
  packages/console/src/App/Stage/Buckets/index.tsx
  packages/console/src/App/Stage/Cognito/index.tsx
  packages/console/src/App/Stage/Functions/Detail.tsx
  packages/console/src/App/Stage/Functions/Invocation.tsx
  packages/console/src/App/Stage/Functions/index.tsx
  packages/console/src/App/Stage/Panel.tsx
  packages/console/src/App/Stage/Stacks/index.tsx
  packages/console/src/App/Stage/components.tsx
  packages/console/src/App/Stage/index.tsx
  packages/console/src/components/Badge.tsx
  packages/console/src/components/Button.tsx
  packages/console/src/components/DropdownMenu.tsx
  packages/console/src/components/Spinner.tsx
  packages/console/src/components/Table.tsx
  packages/console/src/components/Textarea.tsx
  packages/console/src/data/aws/cognito.ts
  packages/console/src/main.tsx
  packages/console/src/stitches.config.ts
  packages/web/package.json
  yarn.lock
Labels: enhancement

#1350 StaticSite: speed up deployment
  packages/cli/test/playground/lib/react-static-site-stack.ts
  packages/resources/assets/StaticSite/custom-resource/cf-invalidate.py
  packages/resources/assets/StaticSite/custom-resource/s3-handler.py
  packages/resources/assets/StaticSite/custom-resource/s3-upload.py
  packages/resources/src/StaticSite.ts
  packages/resources/test/ReactStaticSite.test.ts
  packages/resources/test/StaticSite.test.ts
  packages/resources/test/ViteStaticSite.test.ts
  www/docs/constructs/StaticSite.md
  www/docs/frontend.md
Labels: enhancement

#1357 RDS Explorer Console
  packages/console/package.json
  packages/console/src/App/Stage/Cognito/index.tsx
  packages/console/src/App/Stage/Functions/CWInvocation.tsx
  packages/console/src/App/Stage/Functions/Detail.tsx
  packages/console/src/App/Stage/Functions/Invocation.tsx
  packages/console/src/App/Stage/Panel.tsx
  packages/console/src/App/Stage/RDS/index.tsx
  packages/console/src/App/Stage/components.tsx
  packages/console/src/App/Stage/index.tsx
  packages/console/src/components/Badge.tsx
  packages/console/src/components/Button.tsx
  packages/console/src/components/SidePanel.tsx
  packages/console/src/components/index.ts
  packages/console/src/data/aws/index.ts
  packages/console/src/data/aws/rds.ts
  packages/core/src/runtime/server.ts
  packages/resources/assets/RDS/migrator/index.js
  packages/resources/assets/RDS/migrator/package.json
  packages/resources/assets/RDS/migrator/yarn.lock
  packages/resources/src/Metadata.ts
  packages/resources/src/RDS.ts
  packages/resources/test/RDS.test.ts
  www/docs/constructs/RDS.md
  www/sidebars.js
  yarn.lock
Labels: enhancement

#1365 RDS: add jsdocs
  packages/resources/src/RDS.ts
  www/docs/constructs/RDS.md
Labels: documentation

#1371 Console: fix RDS console crash when app does not have RDS clusters
  packages/console/src/App/Stage/RDS/index.tsx
Labels: bug

#1373 Updating Thundra docs and adding link to #thundra
  www/config.js
  www/docs/about.md
  www/docs/advanced/monitoring.md
  www/docs/design-principles.md
  www/docs/faq.md
Labels: documentation

#1374 Console: GraphQL Explorer
  README.md
  examples/graphql-apollo/stacks/MyStack.ts
  packages/cli/test/playground/lib/apollo-api-stack.ts
  packages/console/package.json
  packages/console/public/graphql.html
  packages/console/src/App/Stage/GraphQL/index.tsx
  packages/console/src/App/Stage/Panel.tsx
  packages/console/src/App/Stage/index.tsx
  packages/console/src/data/aws/api.ts
  packages/resources/src/Api.ts
  packages/resources/src/AppSyncApi.ts
  packages/resources/src/GraphQLApi.ts
  packages/resources/test/GraphQLApi.test.ts
  www/docs/api.md
  www/docs/constructs/GraphQlApi.md
  www/docs/util/Permissions.md
  www/docusaurus.config.js
  www/sidebars.js
  yarn.lock
Labels: enhancement

#1369 Adding docs for the SST Console
  packages/console/README.md
  www/config.js
  www/docs/about.md
  www/docs/auth.md
  www/docs/console.md
  www/docs/constructs/RDS.md
  www/docs/database.md
  www/docs/live-lambda-development.md
  www/docs/packages/cli.md
  www/docs/storage.md
  www/sidebars.js
  www/src/css/custom.css
  www/static/img/console/sst-console-buckets-tab.png
  www/static/img/console/sst-console-cognito-tab.png
  www/static/img/console/sst-console-functions-tab.png
  www/static/img/console/sst-console-homescreen.png
  www/static/img/console/sst-console-local-tab.png
  www/static/img/console/sst-console-rds-tab.png
  www/static/img/console/sst-console-stacks-tab.png
Labels: documentation

#1376 Update docs with GraphQL console
  www/docs/api.md
  www/docs/console.md
  www/docs/constructs/GraphQLApi.md
  www/static/img/console/sst-console-graphql-tab.png
Labels: documentation

#1224 sst-env: add support for SST app directory lookup
  packages/static-site-env/README.md
  packages/static-site-env/bin/scripts.js
  www/docs/frontend.md
  www/docs/packages/static-site-env.md
Labels: enhancement

#1347 static-site-env: remove unused and add missing dependencies
  packages/static-site-env/package.json
Labels: bug

#1387 Allow customizing the debug stack
  packages/cli/assets/debug-stack/bin/index.js
  packages/cli/assets/debug-stack/lib/DebugStack.js
  packages/cli/scripts/remove.js
  packages/cli/scripts/start.js
  packages/cli/test/playground/lib/index.ts
  packages/resources/assets/DebugStack/wsConnect.js
  packages/resources/assets/DebugStack/wsDefault.js
  packages/resources/assets/DebugStack/wsDisconnect.js
  packages/resources/src/DebugApp.ts
  packages/resources/src/DebugStack.ts
  packages/resources/src/index.ts
  www/docs/advanced/permission-boundary.md
  www/docs/advanced/tagging-resources.md
  www/docs/constructs/DebugApp.md
  www/docs/constructs/DebugStack.md
  www/docs/live-lambda-development.md
  www/sidebars.js
Labels: enhancement

#1388 ApiGatewayV1Api: cannot set restApiName
  packages/resources/src/ApiGatewayV1Api.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
Labels: bug

#1389 RDS: fix attachPermission does not grant secretsmanager:GetSecretValue
  packages/resources/src/util/permission.ts
  packages/resources/test/Function.test.ts
Labels: bug

#1396 Prevent loading jsdom, which mocks fetch/XHR
  packages/cli/scripts/util/createJestConfig.js
Labels: bug

#1401 RDS: Fix running migrations on windows
  packages/resources/assets/RDS/migrator/index.js
Labels: bug

#1406 Editing docs for the debug stack
  www/docs/advanced/permission-boundary.md
  www/docs/advanced/tagging-resources.md
  www/docs/constructs/App.md
  www/docs/constructs/DebugApp.md
  www/docs/constructs/DebugStack.md
  www/docs/live-lambda-development.md
  www/sidebars.js
Labels: documentation

#1411 Check for instanceof DebugStack is not reliable inside DebugApp
  packages/resources/src/Construct.ts
  packages/resources/src/DebugApp.ts
Labels: bug

#1414 Copy migration to temp file to bust cache
  packages/resources/assets/RDS/migrator/index.js
  packages/resources/src/Function.ts
Labels: bug

#1412 Auth: import existing UserPool
  packages/cli/test/playground/lib/api-stack.ts
  packages/resources/src/Auth.ts
  packages/resources/test/Auth.test.ts
  www/docs/constructs/Auth.md
Labels: enhancement

#1420 RDS: fixed 0 showing as <null>
  packages/console/src/App/Stage/RDS/index.tsx
Labels: bug

#1419 Update schema compiling for middy example
  examples/middy-validator/package.json
  examples/middy-validator/src/lambda.js
Labels: documentation

#1430 sst start: show descriptive message for "Unable to find function"
  packages/cli/scripts/start.js
Labels: enhancement

#1431 sst start: show descriptive error message when remote Lambda timed out
  packages/cli/scripts/start.js
  packages/cli/test/playground/lib/api-stack.ts
Labels: enhancement

#1413 Allow overriding s3 bucket and function props in debug stack
  packages/resources/src/DebugStack.ts
  www/docs/constructs/DebugStack.md
Labels: enhancement

#1433 Fixed typo
  www/docs/architecture.md
Labels: documentation

#1418 Explorer: Dynamo Console
  .gitignore
  packages/cli/test/playground/lib/index.ts
  packages/console/index.html
  packages/console/package.json
  packages/console/src/App/Stage/Cognito/index.tsx
  packages/console/src/App/Stage/Dynamo/Editor.tsx
  packages/console/src/App/Stage/Dynamo/index.tsx
  packages/console/src/App/Stage/Panel.tsx
  packages/console/src/App/Stage/index.tsx
  packages/console/src/components/Input.tsx
  packages/console/src/components/Row.tsx
  packages/console/src/components/Spinner.tsx
  packages/console/src/components/Tabs.tsx
  packages/console/src/components/index.ts
  packages/console/src/data/aws/dynamodb.ts
  packages/console/src/main.tsx
  packages/console/tsconfig.json
  yarn.lock
Labels: enhancement

#1441 sst start: fix large payload IllegalLocationConstraintException error in new regions
  packages/cli/scripts/start.js
  packages/core/src/runtime/ws.ts
Labels: bug

#1443 sst start: setting NODE_OPTIONS in Lambda environment causes VSCode breakpoint not working
  packages/cli/scripts/start.js
Labels: bug

#1435 Typo in auth.md
  www/docs/auth.md
Labels: documentation
