Repository serverless-stack/sst, pull requests merged in 2022-05, with the labels that each got.

#1660 Handle JSON encoding errors in bootstrap.py
  packages/core/src/runtime/shells/bootstrap.py
Labels: enhancement

#1485 fix: Update dotnet-bootstrap to only run once and exit
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/runtime/handler/dotnet.ts
  packages/core/src/runtime/shells/dotnet-bootstrap/dotnet-bootstrap.csproj
  packages/core/src/runtime/shells/dotnet-bootstrap/release/Amazon.Lambda.Core.dll
  packages/core/src/runtime/shells/dotnet-bootstrap/release/Amazon.Lambda.RuntimeSupport.dll
  packages/core/src/runtime/shells/dotnet-bootstrap/release/System.Runtime.CompilerServices.Unsafe.dll
  packages/core/src/runtime/shells/dotnet-bootstrap/release/System.Text.Encodings.Web.dll
  packages/core/src/runtime/shells/dotnet-bootstrap/release/System.Text.Json.dll
  packages/core/src/runtime/shells/dotnet-bootstrap/release/dotnet-bootstrap
  packages/core/src/runtime/shells/dotnet-bootstrap/release/dotnet-bootstrap.deps.json
  packages/core/src/runtime/shells/dotnet-bootstrap/release/dotnet-bootstrap.dll
  packages/core/src/runtime/shells/dotnet-bootstrap/release/dotnet-bootstrap.pdb
Labels: bug

#1670 Cli: hide site env in deploy output if no env
  packages/cli/scripts/util/cdkHelpers.js
Labels: bug

#1671 Update CDK to 2.22.0
  packages/cli/package.json
  packages/cli/test/playground/package.json
  packages/cli/test/update-from-cdk-v1/package.json
  packages/cli/test/update-from-cdk-v2/package.json
  packages/core/package.json
  packages/resources/package.json
  yarn.lock
Labels: enhancement

#1693 Table: show friendly error message when index key is not defined in fields
  packages/cli/package.json
  packages/cli/test/helpers/setup-tests.js
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/lib/table-stack.ts
  packages/resources/src/Table.ts
  packages/resources/test/Table.test.ts
Labels: bug

#1692 Fixed import typo in expo-app example
  examples/expo-app/backend/lambda.ts
  packages/create-sst/bin/presets/examples/expo-app/templates/backend/lambda.ts
Labels: documentation

#1678 Update migration.md
  www/docs/constructs/v0/migration.md
Labels: documentation

#1694 Update CDK to 2.24.0
  packages/cli/package.json
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/package.json
  packages/cli/test/update-from-cdk-v1/package.json
  packages/cli/test/update-from-cdk-v2/package.json
  packages/core/package.json
  packages/create-sst/bin/presets/base/example/templates/stacks/index.ts
  packages/create-sst/bin/presets/examples/parameter-prototype/templates/stacks/index.ts
  packages/create-sst/bin/presets/starters/graphql-stack/templates/stacks/index.ts
  packages/create-sst/bin/presets/starters/javascript-starter/templates/stacks/index.js
  packages/create-sst/bin/presets/starters/typescript-starter/templates/stacks/index.ts
  packages/resources/package.json
  packages/resources/src/Function.ts
  packages/resources/src/RDS.ts
  packages/resources/src/Script.ts
  packages/resources/src/Stack.ts
  yarn.lock
Labels: enhancement

#1705 Queue: expose queueUrl property
  .changeset/wicked-tables-grin.md
  .gitpod.yml
  packages/resources/src/Queue.ts
  packages/resources/test/Queue.test.ts
Labels: enhancement

#1715 Load dotenv for debug stack
  .changeset/nine-roses-exercise.md
  packages/cli/assets/debug-stack/bin/index.mjs
  packages/cli/scripts/remove.mjs
  packages/cli/scripts/start.mjs
  packages/cli/test/helpers/run-remove-command.js
  packages/core/src/util/environment.ts
Labels: enhancement

#1716 Cron: support disabling cron job
  .changeset/shy-jokes-begin.md
  packages/resources/src/Cron.ts
  packages/resources/test/Cron.test.ts
  www/docs/constructs/Cron.snippets.md
Labels: enhancement

#1724 Update rest api example
  packages/create-sst/bin/presets/examples/rest-api/templates/backend/functions/get.ts
  packages/create-sst/bin/presets/examples/rest-api/templates/backend/functions/update.ts
  packages/create-sst/bin/presets/examples/rest-api/templates/backend/notes.ts
Labels: documentation

#1742 WebSocketApi: add getRoute() to make WebSocketRoute accessible
  .changeset/cyan-geese-decide.md
  packages/resources/src/WebSocketApi.ts
  packages/resources/test/WebSocketApi.test.ts
Labels: enhancement

#1744 NextjsSite: support reusing CloudFront Origin Request Policy
  .changeset/brown-doors-clean.md
  packages/resources/src/NextjsSite.ts
  packages/resources/test/NextjsSite.test.ts
  www/docs/constructs/NextjsSite.md
  www/docs/constructs/NextjsSite.snippets.md
Labels: enhancement

#1747 Updated Auth0 example with React frontend
  packages/create-sst/bin/presets/examples/api-auth-jwt-auth0/templates/backend/functions/private.ts
  packages/create-sst/bin/presets/examples/api-auth-jwt-auth0/templates/frontend/.gitignore
  packages/create-sst/bin/presets/examples/api-auth-jwt-auth0/templates/frontend/index.html
  packages/create-sst/bin/presets/examples/api-auth-jwt-auth0/templates/frontend/package.json
  packages/create-sst/bin/presets/examples/api-auth-jwt-auth0/templates/frontend/src/App.jsx
  packages/create-sst/bin/presets/examples/api-auth-jwt-auth0/templates/frontend/src/favicon.svg
  packages/create-sst/bin/presets/examples/api-auth-jwt-auth0/templates/frontend/src/index.css
  packages/create-sst/bin/presets/examples/api-auth-jwt-auth0/templates/frontend/src/logo.svg
  packages/create-sst/bin/presets/examples/api-auth-jwt-auth0/templates/frontend/src/main.jsx
  packages/create-sst/bin/presets/examples/api-auth-jwt-auth0/templates/frontend/src/sst-env.d.ts
  packages/create-sst/bin/presets/examples/api-auth-jwt-auth0/templates/frontend/vite.config.js
  packages/create-sst/bin/presets/examples/api-auth-jwt-auth0/templates/stacks/MyStack.ts
Labels: documentation

#1756 Updated Cognito JWT example with React frontend
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/backend/functions/private.ts
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/frontend/.gitignore
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/frontend/index.html
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/frontend/package.json
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/frontend/src/App.jsx
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/frontend/src/components/Login.jsx
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/frontend/src/components/Signup.jsx
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/frontend/src/favicon.svg
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/frontend/src/index.css
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/frontend/src/logo.svg
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/frontend/src/main.jsx
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/frontend/src/sst-env.d.ts
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/frontend/vite.config.js
  packages/create-sst/bin/presets/examples/api-auth-jwt-cognito-user-pool/templates/stacks/MyStack.ts
Labels: documentation

#1760 Added Facebook OAuth example
  packages/create-sst/bin/presets/examples/api-oauth-facebook/preset.mjs
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/README.md
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/backend/functions/private.ts
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/backend/functions/public.ts
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/frontend/.gitignore
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/frontend/index.html
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/frontend/package.json
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/frontend/src/App.jsx
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/frontend/src/favicon.svg
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/frontend/src/index.css
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/frontend/src/logo.svg
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/frontend/src/main.jsx
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/frontend/src/sst-env.d.ts
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/frontend/vite.config.js
  packages/create-sst/bin/presets/examples/api-oauth-facebook/templates/stacks/MyStack.ts
Labels: documentation
