Repository serverless-stack/sst, pull requests merged in 2022-03, with the labels that each got.

#1448 sst start: add Lambda contexts required by Lambda power tool logger
  packages/core/src/runtime/server.ts
  packages/core/src/runtime/shells/bootstrap.py
Labels: enhancement

#1439 fix ctrl-c twice issue
  packages/cli/scripts/start.js
Labels: bug

#1449 Function: do not set esbuild "external" without "bundle" is disabled
  packages/core/src/runtime/handler/node.ts
Labels: bug

#1442 Fix lambda transpiling issue in mongodb example
  examples/rest-api-mongodb/package.json
  examples/rest-api-mongodb/src/package.json
  examples/rest-api-mongodb/stacks/MyStack.js
Labels: documentation

#1454 fixed showing the loading sign while creating new folder
  packages/console/src/App/Stage/Buckets/Detail.tsx
Labels: enhancement

#1451 Explorer: API
  packages/cli/fake-OAOUIU/package.json
  packages/cli/fake-OAOUIU/yarn.lock
  packages/console/src/App/Stage/Api/index.tsx
  packages/console/src/App/Stage/Functions/index.tsx
  packages/console/src/App/Stage/Panel.tsx
  packages/console/src/App/Stage/index.tsx
  packages/console/src/components/Input.tsx
  packages/console/src/vite-env.d.ts
Labels: enhancement

#1459 S3: copy signed url of object instead of s3 url
  packages/console/src/App/Stage/Buckets/Detail.tsx
Labels: enhancement

#1460 Console: fix dynamoDB copy
  packages/console/src/App/Stage/Dynamo/index.tsx
Labels: documentation

#1470 Console: fix undefined error stack trace crash
  packages/console/src/App/Stage/Functions/Invocation.tsx
Labels: bug

#1483 Better packaging for @serverless-stack/node
  .yarnrc
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/node/.gitignore
  packages/node/auth/index.d.ts
  packages/node/auth/index.js
  packages/node/graphql/upload.graphql
  packages/node/package.json
  packages/node/src/auth/index.ts
  packages/node/src/config.ts
  packages/node/src/config/index.ts
  packages/node/src/graphql.ts
  packages/node/src/graphql/index.ts
  packages/node/tsconfig.json
  packages/web/package.json
  yarn.lock
Labels: enhancement

#1476 Added example for Angular
  examples/README.md
  examples/angular-app/.gitignore
  examples/angular-app/README.md
  examples/angular-app/frontend/.browserslistrc
  examples/angular-app/frontend/.editorconfig
  examples/angular-app/frontend/.gitignore
  examples/angular-app/frontend/README.md
  examples/angular-app/frontend/angular.json
  examples/angular-app/frontend/karma.conf.js
  examples/angular-app/frontend/package-lock.json
  examples/angular-app/frontend/package.json
  examples/angular-app/frontend/scripts/setenv.ts
  examples/angular-app/frontend/src/app/app.component.css
  examples/angular-app/frontend/src/app/app.component.html
  examples/angular-app/frontend/src/app/app.component.spec.ts
  examples/angular-app/frontend/src/app/app.component.ts
  examples/angular-app/frontend/src/app/app.module.ts
  examples/angular-app/frontend/src/assets/.gitkeep
  examples/angular-app/frontend/src/environments/environment.prod.ts
  examples/angular-app/frontend/src/environments/environment.ts
  examples/angular-app/frontend/src/favicon.ico
  examples/angular-app/frontend/src/index.html
  examples/angular-app/frontend/src/main.ts
  examples/angular-app/frontend/src/polyfills.ts
  examples/angular-app/frontend/src/styles.css
  examples/angular-app/frontend/src/test.ts
  examples/angular-app/frontend/tsconfig.app.json
  examples/angular-app/frontend/tsconfig.json
  examples/angular-app/frontend/tsconfig.spec.json
  examples/angular-app/package.json
  examples/angular-app/src/lambda.js
  examples/angular-app/sst.json
  examples/angular-app/stacks/MyStack.js
  examples/angular-app/stacks/index.js
  examples/angular-app/test/MyStack.test.js
Labels: documentation

#1498 Added kinesis streams in functions tab
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/lib/table-stack.ts
  packages/console/src/App/Stage/Functions/index.tsx
Labels: bug

#1500 Update CDK to 2.15.0
  packages/cli/bin/sync-cdk-version.js
  packages/cli/package.json
  packages/cli/test/playground/package.json
  packages/cli/test/update-from-cdk-v1/package.json
  packages/cli/test/update-from-cdk-v2/package.json
  packages/core/package.json
  packages/resources/package.json
  packages/resources/test/AppSyncApi.test.ts
  yarn.lock
Labels: enhancement

#1508 Fix: do not use dynamic file migrator in production
  packages/resources/assets/RDS/migrator/index.js
Labels: bug

#1501 Update architecture.md
  www/docs/architecture.md
Labels: documentation

#1514 Functional Stacks
  packages/resources/src/App.ts
  packages/resources/src/FunctionalStack.ts
  packages/resources/src/index.ts
  packages/resources/test/FunctionalStack.test.ts
Labels: enhancement

#1512 Added Thundra example
  examples/README.md
  examples/thundra/.env
  examples/thundra/.gitignore
  examples/thundra/README.md
  examples/thundra/config/esbuild.js
  examples/thundra/package.json
  examples/thundra/src/lambda.js
  examples/thundra/sst.json
  examples/thundra/stacks/MyStack.js
  examples/thundra/stacks/index.js
  examples/thundra/test/MyStack.test.js
Labels: documentation

#1529 Update Datadog example to CDK V2
  examples/datadog/package.json
  examples/datadog/stacks/MyStack.js
  examples/datadog/stacks/index.js
  examples/datadog/test/MyStack.test.js
Labels: documentation

#1535 Auth: Fix documentation typo
  www/docs/auth.md
Labels: documentation

#1533 StaticSite: replace environment in all html files
  packages/resources/src/StaticSite.ts
  packages/resources/test/ReactStaticSite.test.ts
  packages/resources/test/StaticSite.test.ts
  packages/resources/test/ViteStaticSite.test.ts
Labels: enhancement

#1541 StaticSite: support removing old files
  packages/resources/assets/BaseSite/archiver.js
  packages/resources/assets/BaseSite/custom-resource/s3-handler.py
  packages/resources/src/StaticSite.ts
  www/docs/constructs/StaticSite.md
Labels: enhancement

#1547 Cli: fix sst cdk command exit code
  packages/cli/scripts/cdk.js
Labels: bug

#1548 Cli: fix invoking CDK cli issue on Windows
  packages/cli/scripts/cdk.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/core/src/index.ts
Labels: bug

#1542 Update Postgres example using RDS construct
  examples/rest-api-postgresql/cdk.context.json
  examples/rest-api-postgresql/package.json
  examples/rest-api-postgresql/src/lambda.js
  examples/rest-api-postgresql/src/migrations/first.js
  examples/rest-api-postgresql/stacks/MyStack.js
  examples/rest-api-postgresql/stacks/index.js
Labels: documentation

#1545 Added Tooltips to icons in sidepanel
  packages/console/src/App/Stage/Panel.tsx
  packages/console/src/components/Tooltip.tsx
Labels: enhancement

#1559 Cli: handle previous exports not imported for auto export check
  packages/core/src/index.ts
Labels: bug

#1571 Fix "Cannot find app handler" when using custom file name in sst.json main entry
  packages/cli/assets/debug-stack/bin/index.js
  packages/cli/scripts/remove.js
  packages/cli/scripts/start.js
  packages/cli/test/playground/sst.json
  packages/core/src/stacks/build.ts
Labels: bug

#1573 Add error helper when cdk cli and constructs use different schema verions
  packages/core/src/errorHelpers.js
Labels: enhancement

#1570 CLI: add support for SSO and --profile option
  packages/cli/bin/scripts.js
  packages/core/package.json
  packages/core/src/aws-sdk/awscli-compatible.ts
  packages/core/src/aws-sdk/index.ts
  www/docs/packages/cli.md
  yarn.lock
Labels: enhancement

#1566 sst-env: fix cannot find environment when custom stack names are used
  packages/cli/scripts/start.js
  packages/cli/scripts/util/cdkHelpers.js
Labels: bug

#1560 Cli: support absolute paths for --outputs-file
  packages/cli/scripts/deploy.js
  packages/cli/scripts/start.js
Labels: enhancement
