Repository serverless-stack/sst, pull requests merged in 2022-01, with the labels that each got.

#1209 Cli: sst start fails when using custom stackName
  packages/core/src/cli/StacksBuilder.ts
Labels: bug

#1212 Turn on typechecking for frontend
  packages/console/package.json
  packages/console/src/App/Stage/Buckets/Detail.tsx
  packages/console/src/App/Stage/Buckets/DetailOld.tsx
  packages/console/src/App/Stage/Buckets/index.tsx
  packages/console/src/components/hooks.ts
  packages/console/src/stitches.config.ts
  packages/console/src/vite-env.d.ts
  packages/console/tsconfig.json
  packages/resources/src/App.ts
  packages/resources/src/util/dotnetBuilder.ts
  packages/resources/src/util/goBuilder.ts
  packages/resources/src/util/nodeBuilder.ts
  packages/resources/src/util/pythonBuilder.ts
Labels: internal

#1211 fix: invocation response ERROR src property must be a valid json object
  packages/console/src/App/Stage/Functions/Invocation.tsx
Labels: bug

#1218 Run prettier on tsx files
  package.json
Labels: skip changelog

#1219 Emit external source maps when bundling for prod
  packages/core/src/runtime/handler/node.ts
Labels: bug

#1227 fix: Dark theme doesn't applied to splash
  packages/console/src/main.tsx
Labels: bug

#1214 Initialize ws server after runtime server
  packages/cli/scripts/start.js
Labels: bug

#1231 fix: do not crop image in preview
  packages/console/src/App/Stage/Buckets/Detail.tsx
Labels: bug

#1237 Remove metadata tests
  packages/resources/test/Api.test.ts
  packages/resources/test/ApiGatewayV1Api.test.ts
  packages/resources/test/App.test.ts
  packages/resources/test/AppSyncApi.test.ts
  packages/resources/test/Auth.test.ts
  packages/resources/test/Bucket.test.ts
  packages/resources/test/Cron.test.ts
  packages/resources/test/EventBus.test.ts
  packages/resources/test/Function.test.ts
  packages/resources/test/KinesisStream.test.ts
  packages/resources/test/Queue.test.ts
  packages/resources/test/Table.test.ts
  packages/resources/test/Topic.test.ts
  packages/resources/test/WebSocketApi.test.ts
Labels: internal

#1235 Limit how fast stack metadata is fetched
  packages/console/src/data/aws/stacks.ts
Labels: bug

#1217 fix: Leave the function request body after an invocation
  packages/console/src/App/Stage/Functions/Detail.tsx
Labels: enhancement

#1215 fix: show sign if bucket is empty
  packages/console/src/App/Stage/Buckets/Detail.tsx
Labels: bug

#1238 Page through all cloudformation stacks
  packages/console/src/data/aws/stacks.ts
Labels: bug

#1240 Filter out stacks that do not match supported console version
  packages/console/src/data/aws/stacks.ts
Labels: enhancement

#1242 Update CDK to v1.138.0
  packages/cli/package.json
  packages/cli/test/base-dotnet/package.json
  packages/cli/test/base-go/package.json
  packages/cli/test/base-python/package.json
  packages/cli/test/base-ts/package.json
  packages/cli/test/base-tsx/package.json
  packages/cli/test/base/package.json
  packages/cli/test/config-main-js/package.json
  packages/cli/test/config-main-ts/package.json
  packages/cli/test/config/package.json
  packages/cli/test/context/package.json
  packages/cli/test/dotenv/package.json
  packages/cli/test/dotnet-build/package.json
  packages/cli/test/go-build/package.json
  packages/cli/test/is-local/package.json
  packages/cli/test/jest-ts/package.json
  packages/cli/test/jest/package.json
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/lib/websocket-api-stack.ts
  packages/cli/test/playground/package.json
  packages/cli/test/remove/package.json
  packages/cli/test/rest-api-auth-cognito/package.json
  packages/cli/test/stack-no-prefix/package.json
  packages/cli/test/start-base/package.json
  packages/cli/test/start-demo/package.json
  packages/cli/test/start-guide/package.json
  packages/cli/test/start-handler-sync-async-cases/package.json
  packages/cli/test/start-no-src-path/package.json
  packages/cli/test/template-app-ts/package.json
  packages/cli/test/template-app/package.json
  packages/cli/test/update/package.json
  packages/core/package.json
  packages/resources/package.json
  packages/resources/src/Api.ts
  packages/resources/src/ApolloApi.ts
  packages/resources/src/WebSocketApi.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/ApolloApi.test.ts
  packages/resources/test/KinesisStream.test.ts
  packages/resources/test/WebSocketApi.test.ts
  www/docs/constructs/WebSocketApi.md
  yarn.lock
Labels: enhancement

#1244 Require build function for handler
  packages/core/src/runtime/handler/definition.ts
  packages/core/src/runtime/handler/python.ts
Labels: bug

#1233 fix: do not use a remote svg image in preview
  packages/console/src/App/Stage/Buckets/Detail.tsx
Labels: internal

#1248 Fix bundle disabling
  packages/core/src/runtime/handler/node.ts
Labels: bug

#1236 Cli: Add anonymous telemetry collection
  packages/cli/bin/scripts.js
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/telemetry/environment.ts
  packages/core/src/telemetry/index.ts
  packages/core/src/telemetry/post-payload.ts
  packages/core/src/telemetry/project-id.ts
  packages/core/src/telemetry/telemetry.ts
  www/docs/anonymous-telemetry.md
  www/docs/packages/cli.md
  www/sidebars.js
  yarn.lock
Labels: enhancement

#1254 Fix a typo in anonymous-telemetry.md
  www/docs/anonymous-telemetry.md
Labels: documentation

#1255 Add tests for telemetry project id parsing
  package.json
  packages/core/jest.config.js
  packages/core/package.json
  packages/core/src/telemetry/project-id.ts
  packages/core/test/telemetry/telemetry.test.ts
Labels: skip changelog

#1258 Cdk v2 doc
  packages/cli/scripts/add-cdk.js
  www/docs/constructs/Api.md
  www/docs/constructs/ApiGatewayV1Api.md
  www/docs/constructs/ApolloApi.md
  www/docs/constructs/App.md
  www/docs/constructs/AppSyncApi.md
  www/docs/constructs/Auth.md
  www/docs/constructs/Bucket.md
  www/docs/constructs/Cron.md
  www/docs/constructs/EventBus.md
  www/docs/constructs/Function.md
  www/docs/constructs/KinesisStream.md
  www/docs/constructs/NextjsSite.md
  www/docs/constructs/Queue.md
  www/docs/constructs/ReactStaticSite.md
  www/docs/constructs/Script.md
  www/docs/constructs/Stack.md
  www/docs/constructs/StaticSite.md
  www/docs/constructs/Table.md
  www/docs/constructs/Topic.md
  www/docs/constructs/WebSocketApi.md
  www/docs/design-principles.md
  www/docs/faq.md
  www/docs/known-issues.md
  www/docs/live-lambda-development.md
  www/docs/migrating-from-serverless-framework.md
  www/docs/monitoring-your-app-in-prod.md
  www/docs/packages/cli.md
  www/docs/util/Permissions.md
  www/docs/working-locally.md
Labels: skip changelog

#1252 Do not do anything special for Go directory handlers
  packages/core/src/runtime/handler/go.ts
  packages/resources/src/Function.ts
Labels: bug

#1261 Update cdkHelpers to verify CDK mismatch versions
  packages/cli/scripts/add-cdk.js
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/add-cdk/add-cdk.test.js
  packages/cli/test/cdkHelpers/cdkHelpers.test.js
  packages/cli/test/mismatched-cdk-versions/lib/cognito.js
  packages/cli/test/mismatched-cdk-versions/lib/dynamodb.js
  packages/cli/test/mismatched-cdk-versions/lib/index.js
  packages/cli/test/mismatched-cdk-versions/lib/s3.js
  packages/cli/test/mismatched-cdk-versions/mismatched-cdk-versions.test.js
  packages/cli/test/mismatched-cdk-versions/package.json
  packages/cli/test/mismatched-cdk-versions/sst.json
  yarn.lock
Labels: skip changelog

#1263 Cli: fix accounts not automatically bootstrapped
  packages/core/src/index.ts
Labels: bug

#1138 added external custom domain support to Api construct
  packages/resources/src/util/apiGatewayV2Domain.ts
  packages/resources/test/Api.test.ts
  packages/resources/test/WebSocketApi.test.ts
  www/docs/constructs/Api.md
  www/docs/constructs/StaticSite.md
  www/docs/constructs/WebSocketApi.md
Labels: enhancement, pkg: resources/Api

#1266 Permissions: support Kinesis Firehose Delivery Stream
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/lib/kinesis-firehose.ts
  packages/cli/test/playground/package.json
  packages/resources/src/util/permission.ts
  www/docs/util/Permissions.md
  yarn.lock
Labels: enhancement

#1268 Remove node-fetch
  packages/core/src/telemetry/post-payload.ts
Labels: internal

#1267 Update esbuild and remove sourcemaps
  package.json
  packages/cli/assets/console/package.json
  packages/core/package.json
  packages/core/src/runtime/handler/node.ts
  yarn.lock
Labels: enhancement

#1270 Bring back sourcemap
  packages/core/src/runtime/handler/node.ts
Labels: internal

#1272 Cli: fix stacks with custom stack name fail to deploy
  packages/cli/scripts/build.js
  packages/cli/scripts/deploy.js
  packages/cli/scripts/diff.js
  packages/cli/scripts/remove.js
  packages/core/src/cli/StacksBuilder.ts
  packages/core/src/index.ts
Labels: bug

#1273 Remove asset deps in cdk v2 manifest
  packages/core/src/index.ts
Labels: skip changelog

#1274 Support ESM format
  packages/core/src/runtime/handler/node.ts
  packages/resources/src/Function.ts
  www/docs/constructs/Function.md
Labels: enhancement

#1275 Cli: fix cdk bootstrap version mismatch
  packages/core/src/index.ts
Labels: bug

#1281 Update readme examples link
  examples/README.md
Labels: documentation

#1284 Use relative path to pass in handler to ric
  packages/cli/package.json
  yarn.lock
Labels: bug

#1286 GraphQLApi Construct
  packages/cli/scripts/start.js
  packages/resources/src/ApolloApi.ts
  packages/resources/src/App.ts
  packages/resources/src/Construct.ts
  packages/resources/src/GraphQLApi.ts
  packages/resources/src/Metadata.ts
  packages/resources/src/index.ts
Labels: enhancement

#1298 Set aws-cdk-lib as external when transpiling CDK code
  packages/core/src/stacks/build.ts
Labels: bug

#1301 Cli: disable xray tracing for local invocation
  packages/core/src/runtime/server.ts
Labels: bug

#1302 NextjsSite: fix placeholder lambda functions
  packages/resources/assets/Function/placeholder-stub/lambda.js
  packages/resources/assets/NextjsSite/edge-lambda-stub/index.js
Labels: bug

#1308 Cli: fix stack changes not redeployed in sst start
  packages/cli/test/playground/lib/circular-dependency-stack.ts
  packages/core/src/cli/StacksBuilder.ts
  packages/core/src/local/server.ts
  packages/resources/src/util/apiGatewayV2Domain.ts
Labels: bug

#1310 Cli: detect exports still in use and temporarily add to template
  packages/cli/test/playground/lib/api-stack.ts
  packages/cli/test/playground/lib/index.ts
  packages/core/src/index.ts
Labels: enhancement

#1311 Cli: hide exports from outputs created by CDK
  packages/cli/scripts/util/cdkHelpers.js
  packages/cli/test/playground/output.json
Labels: enhancement

#1288 Add ViteStaticSite construct
  README.md
  packages/resources/src/ViteStaticSite.ts
  packages/resources/src/index.ts
  packages/resources/test/ViteStaticSite.test.ts
  packages/resources/test/vite-static-site/js-site/.gitignore
  packages/resources/test/vite-static-site/js-site/build/index.html
  packages/resources/test/vite-static-site/js-site/error.html
  packages/resources/test/vite-static-site/js-site/index.html
  packages/resources/test/vite-static-site/js-site/package.json
  packages/resources/test/vite-static-site/ts-site/.gitignore
  packages/resources/test/vite-static-site/ts-site/build/index.html
  packages/resources/test/vite-static-site/ts-site/error.html
  packages/resources/test/vite-static-site/ts-site/index.html
  packages/resources/test/vite-static-site/ts-site/package.json
  packages/resources/test/vite-static-site/ts-site/tsconfig.json
  www/docs/constructs/ReactStaticSite.md
  www/docs/constructs/ViteStaticSite.md
  www/sidebars.js
Labels: enhancement

#1295 Add RDS construct
  packages/cli/test/playground/cdk.context.json
  packages/cli/test/playground/lib/index.ts
  packages/cli/test/playground/lib/rds-stack.ts
  packages/cli/test/playground/src/rds/migrations/mysql/base.js
  packages/cli/test/playground/src/rds/migrations/postgres/base.js
  packages/cli/test/playground/src/rds/migrations/postgres/z20220123.js
  packages/cli/test/playground/src/rds/migrations/postgres/z20220123b.js
  packages/core/src/runtime/handler/node.ts
  packages/resources/assets/RDS/migrator/index.js
  packages/resources/assets/RDS/migrator/package.json
  packages/resources/assets/RDS/migrator/yarn.lock
  packages/resources/package.json
  packages/resources/src/RDS.ts
  packages/resources/src/index.ts
  packages/resources/src/util/permission.ts
  packages/resources/test/Function.test.ts
  packages/resources/test/RDS.test.ts
  packages/resources/test/rds/migrations/base.js
  www/docs/constructs/RDS.md
  www/sidebars.js
Labels: enhancement

#1313 Cli: stage prompt causes cli to not quit cleanly
  packages/cli/bin/scripts.js
  packages/cli/scripts/start.js
Labels: bug

#1314 RDS: fix bundling with absolute srcPath on windows
  packages/core/src/runtime/handler/node.ts
  packages/resources/bin/copy-rds-migrator.js
  packages/resources/package.json
  packages/resources/test/Function.test.ts
Labels: skip changelog

#1316 Cli: fix build error when folder path contain spaces
  packages/cli/scripts/start.js
Labels: bug

#1317 Function: add support for Python 3.9
  packages/resources/src/Function.ts
Labels: enhancement

#1250 NextjsSite: make image regenerator customizable
  packages/resources/src/NextjsSite.ts
  packages/resources/test/NextjsSite.test.ts
  www/docs/constructs/NextjsSite.md
Labels: enhancement

#1304 New layout for console
  packages/cli/scripts/start.js
  packages/console/public/logo.svg
  packages/console/src/App/Stage/Buckets/Detail.tsx
  packages/console/src/App/Stage/Buckets/index.tsx
  packages/console/src/App/Stage/Cognito/index.tsx
  packages/console/src/App/Stage/Functions/Invocation.tsx
  packages/console/src/App/Stage/Panel.tsx
  packages/console/src/App/Stage/components.tsx
  packages/console/src/App/Stage/index.tsx
  packages/console/src/components/Accordion.tsx
  packages/console/src/components/DropdownMenu.tsx
  packages/console/src/components/Logo.tsx
  packages/console/src/components/Splash.tsx
  packages/console/src/components/Table.tsx
  packages/console/src/data/global.ts
  packages/console/src/main.tsx
  packages/console/src/stitches.config.ts
  packages/core/src/runtime/handler/node.ts
Labels: enhancement

#1319 Fix for esbuild native import issue when using ESM
  packages/core/src/runtime/handler/node.ts
Labels: bug

#1320 Tweaking styles for docs site
  www/config.js
  www/docusaurus.config.js
  www/src/css/custom.css
  www/static/img/star.svg
Labels: documentation
